// Domain 3: Applications of Foundation Models (140 questions)
const D3 = [
  {id:"q221",domain:3,subdomain:"3.1",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Cuáles son los factores principales para elegir un modelo de foundation específico en Amazon Bedrock para una aplicación empresarial?",
  options:[{key:"A",text:"El único factor es el precio por token."},{key:"B",text:"Capacidades del modelo (razonamiento, código, imágenes), calidad en la tarea específica, latencia requerida, costo por token, límite de contexto, idiomas soportados y requisitos de cumplimiento."},{key:"C",text:"Solo la velocidad de respuesta importa para aplicaciones en producción."},{key:"D",text:"Siempre se debe elegir el modelo más grande disponible para máxima calidad."}],
  answer:"B",
  explanation:"La selección del FM correcto requiere evaluar: ¿el modelo es bueno en la tarea específica (código, análisis, creación)? ¿tiene suficiente ventana de contexto? ¿la latencia cumple el SLA? ¿el costo es viable al escalar? ¿cumple requisitos de residencia de datos y privacidad? Bedrock Model Evaluation ayuda a comparar modelos antes de comprometerse."},

  {id:"q222",domain:3,subdomain:"3.1",service:null,difficulty:"medium",
  question:"¿Cuándo es más apropiado construir una aplicación con RAG versus fine-tuning en un FM?",
  options:[{key:"A",text:"RAG siempre es mejor; el fine-tuning nunca aporta valor adicional."},{key:"B",text:"RAG es mejor cuando se necesita información actualizable, diversa o privada con fuentes citables y sin reentrenamiento; fine-tuning es mejor cuando se necesita un estilo, tono o dominio muy específico que no se logra con prompting."},{key:"C",text:"Fine-tuning siempre es mejor porque el modelo aprende la información de forma permanente."},{key:"D",text:"No hay diferencia práctica entre ambos enfoques."}],
  answer:"B",
  explanation:"RAG: ideal para Q&A sobre documentos internos que cambian, información actualizada, reducir alucinaciones con fuentes verificables. Fine-tuning: ideal para adaptar el estilo de comunicación de la marca, especializar en terminología técnica que el modelo base no domina, o mejorar el seguimiento de instrucciones muy específicas del dominio. A menudo se combinan."},

  {id:"q223",domain:3,subdomain:"3.1",service:null,difficulty:"hard",
  question:"¿Qué es el 'training-serving skew' en aplicaciones de Foundation Models y cómo se mitiga?",
  options:[{key:"A",text:"La diferencia de velocidad entre el entrenamiento del modelo y la velocidad de respuesta en producción."},{key:"B",text:"La discrepancia entre la distribución de datos con que se entrenó/fine-tuneó el modelo y los datos reales que llegan en producción, causando degradación de rendimiento."},{key:"C",text:"Un problema técnico de incompatibilidad entre versiones del framework de ML."},{key:"D",text:"La diferencia de costos entre entrenar el modelo y ejecutarlo en producción."}],
  answer:"B",
  explanation:"Si el modelo se fine-tuneó con ejemplos de Q&A formal pero en producción los usuarios escriben coloquialmente, el rendimiento se degrada. Mitigaciones: curar datos de fine-tuning representativos del uso real, monitoreo de distribución de entradas en producción, re-fine-tuning periódico con datos de producción reales."},

  {id:"q224",domain:3,subdomain:"3.1",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Qué consideraciones de latencia y throughput son importantes al diseñar aplicaciones con Amazon Bedrock?",
  options:[{key:"A",text:"La latencia es siempre la misma independientemente del modelo y el prompt."},{key:"B",text:"La latencia aumenta con el tamaño del modelo y la longitud del prompt/respuesta; el streaming reduce la latencia percibida; el throughput se puede garantizar con Provisioned Throughput; modelos más pequeños ofrecen menor latencia."},{key:"C",text:"Solo los modelos de Anthropic tienen latencia variable; los demás son predecibles."},{key:"D",text:"La latencia no es relevante para aplicaciones de IA generativa."}],
  answer:"B",
  explanation:"Consideraciones de latencia en Bedrock: (1) Time to first token (TTFT): con streaming, el usuario ve la primera palabra rápido, mejorando UX. (2) Tokens per second: modelos más pequeños son más rápidos. (3) Prompt caching: Bedrock puede cachear el prefijo del prompt para reducir latencia en contextos repetidos. (4) Provisioned Throughput garantiza throughput constante."},

  {id:"q225",domain:3,subdomain:"3.1",service:null,difficulty:"medium",
  question:"¿Qué es el 'system prompt' en una aplicación basada en LLMs y cuál es su importancia?",
  options:[{key:"A",text:"Un mensaje de error del sistema que aparece cuando el LLM falla."},{key:"B",text:"Instrucciones previas al inicio de la conversación que establecen el rol, comportamiento, restricciones y personalidad del asistente, manteniéndose constantes independientemente de las preguntas del usuario."},{key:"C",text:"Un log del sistema que registra todas las interacciones con el modelo."},{key:"D",text:"El identificador técnico del modelo que se invoca en Bedrock."}],
  answer:"B",
  explanation:"El system prompt define: el rol del asistente ('eres un experto en soporte técnico de software'), restricciones de comportamiento ('nunca discutas temas fuera de soporte técnico'), tono y formato de respuesta, y contexto de la empresa. Es la primera capa de personalización y control del comportamiento del LLM en la aplicación."},

  {id:"q226",domain:3,subdomain:"3.1",service:null,difficulty:"hard",
  question:"¿Qué arquitectura se recomienda para un chatbot empresarial que necesita manejar preguntas sobre documentos internos Y ejecutar acciones en sistemas de la empresa?",
  options:[{key:"A",text:"Un LLM básico con un prompt muy largo que incluya todos los documentos."},{key:"B",text:"Bedrock Agents conectado a Bedrock Knowledge Bases (para RAG sobre documentos) y action groups con funciones Lambda (para ejecutar acciones en sistemas externos como CRM, ERP)."},{key:"C",text:"Amazon Lex con respuestas estáticas para las preguntas más comunes."},{key:"D",text:"Un modelo fine-tuneado con todos los documentos y procedimientos internos."}],
  answer:"B",
  explanation:"La arquitectura óptima combina: Bedrock Knowledge Bases para RAG (responde preguntas sobre documentos con fuentes citables), Bedrock Agents para orquestar el razonamiento multi-paso y llamar a action groups (funciones Lambda que interactúan con APIs del CRM, ERP, calendarios, etc.), con Guardrails para seguridad."},

  {id:"q227",domain:3,subdomain:"3.1",service:null,difficulty:"medium",
  question:"¿Cómo se gestiona el 'contexto de conversación' en una aplicación de chatbot basada en LLMs?",
  options:[{key:"A",text:"El LLM recuerda automáticamente todas las conversaciones previas sin configuración."},{key:"B",text:"El desarrollador debe incluir explícitamente el historial de conversación en cada llamada a la API, gestionando la memoria externamente (base de datos) y resumiendo conversaciones largas para no exceder el límite de contexto."},{key:"C",text:"El contexto de conversación se almacena automáticamente en Amazon S3."},{key:"D",text:"El LLM mantiene contexto indefinido sin límite de tokens por diseño."}],
  answer:"B",
  explanation:"Los LLMs son stateless: cada llamada a la API es independiente. Para historial de conversación: (1) Incluir mensajes previos en el contexto (funciona hasta el límite de tokens). (2) Resumen automático de conversaciones largas. (3) Bases de datos de memoria (Redis, DynamoDB) para recuperar contexto relevante. Bedrock Agents gestiona esto automáticamente en sus sesiones."},

  {id:"q228",domain:3,subdomain:"3.1",service:null,difficulty:"medium",
  question:"¿Qué es el 'chunking' de documentos en sistemas RAG y cómo afecta la calidad de las respuestas?",
  options:[{key:"A",text:"El proceso de comprimir documentos para reducir el uso de almacenamiento en S3."},{key:"B",text:"La división de documentos largos en fragmentos (chunks) de tamaño apropiado para la vectorización y recuperación; chunks muy pequeños pierden contexto, chunks muy grandes reducen precisión y aumentan ruido."},{key:"C",text:"La eliminación de secciones irrelevantes de documentos antes de la indexación."},{key:"D",text:"La traducción automática de documentos a inglés para mejor procesamiento del LLM."}],
  answer:"B",
  explanation:"El chunking es crítico en RAG: chunks muy pequeños (ej. 100 tokens) pierden el contexto necesario para responder bien; chunks muy grandes (ej. 2000 tokens) traen mucho ruido. Estrategias: chunk fijo, chunk por semántica (párrafos/secciones), jerárquico (parent-child), con solapamiento (overlap) entre chunks para no perder información en bordes."},

  {id:"q229",domain:3,subdomain:"3.1",service:"Amazon Bedrock",difficulty:"hard",
  question:"¿Qué es el 'Prompt Caching' de Amazon Bedrock y qué beneficios ofrece?",
  options:[{key:"A",text:"Un sistema de caché de respuestas que devuelve respuestas idénticas para prompts repetidos."},{key:"B",text:"Una funcionalidad que almacena los estados de atención (KV cache) de prefijos de prompts largos y repetitivos, reduciendo la latencia y el costo hasta en un 90% cuando el mismo contexto largo se reutiliza en múltiples solicitudes."},{key:"C",text:"Un sistema de caché de DNS para acelerar las llamadas a la API de Bedrock."},{key:"D",text:"El almacenamiento de modelos en SSD para reducir el tiempo de carga."}],
  answer:"B",
  explanation:"El Prompt Caching (disponible con Claude en Bedrock) permite marcar prefijos del prompt como cacheables. Cuando el mismo system prompt largo, documentos o contexto se envía repetidamente, el KV cache reutiliza los estados de atención pre-calculados. Reducción: hasta 90% en costo de tokens en cache hit, menor latencia en llamadas sucesivas."},

  {id:"q230",domain:3,subdomain:"3.1",service:null,difficulty:"medium",
  question:"¿Qué consideraciones de costo hay que tener en cuenta al diseñar una aplicación de IA generativa con FMs?",
  options:[{key:"A",text:"El único costo es el precio por API call, independientemente del tamaño del prompt."},{key:"B",text:"Costo por token de entrada y salida (varía por modelo), tamaño del contexto (prompts largos = más tokens), frecuencia de llamadas, uso de Provisioned Throughput vs on-demand, costo de almacenamiento de embeddings y bases vectoriales."},{key:"C",text:"Los modelos open-source en Bedrock son completamente gratuitos."},{key:"D",text:"Solo hay costos si el modelo genera más de 1000 tokens por respuesta."}],
  answer:"B",
  explanation:"Optimización de costos en IA generativa: (1) Elegir el modelo más pequeño que cumpla los requisitos de calidad (Claude Haiku vs Sonnet). (2) Prompt caching para contextos repetitivos. (3) Limitar longitud de respuesta. (4) Comprimir el contexto de conversación. (5) Batch inference para procesamiento no urgente. (6) Provisioned Throughput para cargas predecibles de alto volumen."},

  {id:"q231",domain:3,subdomain:"3.1",service:null,difficulty:"medium",
  question:"¿Qué son los 'agentes multi-step' y cuáles son sus ventajas sobre las respuestas directas de un LLM?",
  options:[{key:"A",text:"Agentes que necesitan múltiples intentos para generar una respuesta de calidad."},{key:"B",text:"Sistemas donde el LLM puede descomponer tareas complejas en sub-tareas, ejecutar herramientas secuencialmente, observar resultados e iterar, permitiendo completar objetivos que requieren múltiples pasos de razonamiento y acción."},{key:"C",text:"Modelos que combinan múltiples LLMs en paralelo para mayor precisión."},{key:"D",text:"Sistemas que requieren validación humana en cada paso antes de continuar."}],
  answer:"B",
  explanation:"Un agente multi-step puede: (1) Analizar un PDF, (2) Buscar información relacionada en la web, (3) Calcular métricas con código Python, (4) Actualizar una base de datos, (5) Enviar un resumen por email. Cada paso usa el resultado del anterior. Un LLM simple solo respondería con una única generación sin ejecutar acciones reales."},

  {id:"q232",domain:3,subdomain:"3.1",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Cómo se integran las bases de datos vectoriales con Amazon Bedrock Knowledge Bases para RAG?",
  options:[{key:"A",text:"Bedrock Knowledge Bases solo puede usar DynamoDB como base de datos."},{key:"B",text:"Bedrock Knowledge Bases gestiona automáticamente la ingestión (S3 → chunks → embeddings via Titan Embeddings → indexación en la DB vectorial elegida: OpenSearch Serverless, pgvector, Redis OSS, Pinecone o Mongo Atlas)."},{key:"C",text:"Se requiere construir el pipeline de embeddings manualmente usando Lambda."},{key:"D",text:"Solo soporta bases vectoriales en la región us-east-1."}],
  answer:"B",
  explanation:"El flujo de Bedrock Knowledge Bases: (1) Conectar fuente de datos (S3, Confluence, SharePoint, web crawler), (2) Configurar estrategia de chunking, (3) Seleccionar modelo de embeddings (Titan Embeddings), (4) Seleccionar DB vectorial (OpenSearch Serverless es el default). La sincronización se puede programar o disparar manualmente. Todo gestionado por AWS."},

  {id:"q233",domain:3,subdomain:"3.1",service:null,difficulty:"hard",
  question:"¿Cuáles son los trade-offs de usar un modelo más pequeño y especializado versus uno grande y general para una tarea específica?",
  options:[{key:"A",text:"Los modelos pequeños siempre son peores; solo los grandes son útiles en producción."},{key:"B",text:"Modelos pequeños especializados: menor latencia, menor costo, pueden superar en la tarea específica. Modelos grandes generales: mejor en tareas diversas y no vistas, mayor robustez, pero más caros y lentos. La elección depende del caso de uso y volumen."},{key:"C",text:"Los modelos grandes siempre superan a los especializados en cualquier tarea."},{key:"D",text:"No hay trade-offs relevantes; la decisión es solo de preferencia personal."}],
  answer:"B",
  explanation:"Los modelos pequeños fine-tuneados (7B especializado) pueden superar a modelos grandes generales (70B) en una tarea específica a una fracción del costo. Ej: un modelo de 7B fine-tuneado para clasificación de tickets de soporte puede superar a Claude Opus en esa tarea específica a 10x menor costo. El benchmark en el caso de uso real es la forma correcta de decidir."},

  {id:"q234",domain:3,subdomain:"3.1",service:null,difficulty:"medium",
  question:"¿Qué es la 'orquestación de LLMs' y qué frameworks/servicios la facilitan en AWS?",
  options:[{key:"A",text:"El proceso de gestionar el hardware de servidores que ejecutan los modelos."},{key:"B",text:"El diseño y ejecución de flujos de trabajo complejos que coordinan múltiples llamadas a LLMs, herramientas externas, memoria y decisiones; facilitado por Bedrock Agents, LangChain, LlamaIndex integrados con Bedrock."},{key:"C",text:"La sincronización de múltiples modelos para asegurar respuestas consistentes."},{key:"D",text:"El proceso de balanceo de carga entre múltiples instancias del mismo modelo."}],
  answer:"B",
  explanation:"La orquestación LLM gestiona: qué modelo usar en cada paso, cuándo llamar a qué herramienta, cómo manejar el contexto y la memoria, cómo estructurar el flujo de decisiones. AWS Bedrock Agents proporciona orquestación nativa. LangChain y LlamaIndex (frameworks open-source) se integran con Bedrock como backend del modelo."},

  {id:"q235",domain:3,subdomain:"3.1",service:null,difficulty:"medium",
  question:"¿Qué es el 'output parsing' en aplicaciones de LLMs y por qué es importante?",
  options:[{key:"A",text:"El proceso de comprimir la respuesta del LLM para reducir el uso de ancho de banda."},{key:"B",text:"La extracción y estructuración de información específica de la respuesta de texto libre del LLM (ej. JSON, JSON schema, campos específicos) para integrarlo con sistemas downstream."},{key:"C",text:"La validación ortográfica de las respuestas del LLM antes de mostrarlas al usuario."},{key:"D",text:"La traducción automática de las respuestas del modelo al idioma del usuario."}],
  answer:"B",
  explanation:"Los LLMs generan texto libre; las aplicaciones necesitan datos estructurados. Output parsing: instruir al LLM a responder en JSON, extraer campos específicos con regex/pydantic, usar structured output (JSON mode) si el modelo lo soporta. Ej: 'Extrae nombre, email y teléfono del siguiente texto y devuelve en JSON con estos campos: {name, email, phone}'."},

  {id:"q236",domain:3,subdomain:"3.2",service:null,difficulty:"easy",
  question:"¿Cuál es el propósito principal del 'few-shot prompting' y cómo funciona?",
  options:[{key:"A",text:"Usar el modelo con muy pocos tokens para reducir costos."},{key:"B",text:"Incluir 2-5 ejemplos de entrada-salida en el prompt para demostrar el formato y comportamiento esperado, guiando al modelo a seguir el mismo patrón en la nueva solicitud."},{key:"C",text:"Entrenar el modelo con un dataset pequeño de pocas muestras."},{key:"D",text:"Reducir el tamaño del modelo a few-shot (pocos parámetros)."}],
  answer:"B",
  explanation:"Few-shot prompting incluye ejemplos: 'Clasifica el sentimiento:\nTexto: Me encantó → Positivo\nTexto: Fue terrible → Negativo\nTexto: Estuvo bien → [el modelo completa con Neutral]'. Los ejemplos establecen el formato de respuesta esperado, el estilo y el nivel de detalle. Muy efectivo para tareas de clasificación, extracción y transformación."},

  {id:"q237",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Qué es el 'role prompting' (prompting con rol) y cuándo es efectivo?",
  options:[{key:"A",text:"Asignar diferentes prompts a diferentes roles de usuario en el sistema."},{key:"B",text:"Instruir al LLM a adoptar un rol específico ('actúa como un experto en seguridad informática') para obtener respuestas más especializadas y apropiadas para el contexto."},{key:"C",text:"Un sistema de permisos basado en roles para controlar qué prompts puede enviar cada usuario."},{key:"D",text:"La asignación automática del prompt más adecuado según el perfil del usuario."}],
  answer:"B",
  explanation:"El role prompting establece un contexto de expertise: 'Eres un médico especialista en cardiología con 20 años de experiencia. Explica la siguiente condición de manera comprensible para un paciente'. El modelo adapta su vocabulario, nivel de detalle y perspectiva al rol indicado, mejorando la relevancia y calidad de las respuestas."},

  {id:"q238",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Cuál es la técnica de 'delimitadores' en prompt engineering y por qué se usa?",
  options:[{key:"A",text:"Establecer límites de tokens máximos en la respuesta del modelo."},{key:"B",text:"Usar marcadores especiales (```, XML tags, ###) para separar claramente las instrucciones del contenido a procesar, evitando que el modelo confunda qué es instrucción y qué son datos."},{key:"C",text:"Delimitar el horario de operación de la aplicación basada en el LLM."},{key:"D",text:"Establecer los límites de velocidad de la API del modelo."}],
  answer:"B",
  explanation:"Los delimitadores evitan confusión entre instrucciones y datos: 'Resume el siguiente texto delimitado por triple backtick: ```[texto a resumir]```'. Sin delimitadores, el modelo podría confundir instrucciones en el texto con instrucciones propias. También protege contra prompt injection cuando el texto proviene del usuario."},

  {id:"q239",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Qué es el 'meta-prompting' y cuál es su utilidad práctica?",
  options:[{key:"A",text:"Un prompt que controla el comportamiento de múltiples modelos simultáneamente."},{key:"B",text:"Usar un LLM para generar o mejorar prompts para otro LLM (o para sí mismo), optimizando automáticamente las instrucciones para obtener mejores respuestas."},{key:"C",text:"La documentación técnica de los prompts usados en producción."},{key:"D",text:"Un sistema de versionado de prompts para control de cambios."}],
  answer:"B",
  explanation:"El meta-prompting usa el LLM como optimizador de prompts: 'Tengo el siguiente prompt que no está dando buenos resultados: [prompt]. ¿Cómo lo mejorarías para [objetivo]?'. También: generación automática de prompts para fine-tuning, optimización automática de prompts (AutoPrompt). Útil para equipos sin experiencia en prompt engineering."},

  {id:"q240",domain:3,subdomain:"3.2",service:null,difficulty:"hard",
  question:"¿Qué es el 'tree of thoughts' (ToT) y en qué se diferencia del chain-of-thought?",
  options:[{key:"A",text:"Una técnica para visualizar el árbol de decisiones interno del modelo."},{key:"B",text:"Una extensión del CoT que permite al modelo explorar múltiples ramas de razonamiento en paralelo y retroceder cuando una rama no es prometedora, similar a búsqueda con backtracking para problemas complejos."},{key:"C",text:"Una arquitectura de modelo en árbol para mejor razonamiento jerárquico."},{key:"D",text:"Un método para organizar múltiples LLMs en una estructura de árbol para consultas."}],
  answer:"B",
  explanation:"Tree of Thoughts generaliza CoT: en vez de una cadena lineal de razonamiento, el modelo genera múltiples pensamientos candidatos, los evalúa y explora los más prometedores (como BFS/DFS). Muy efectivo para problemas que requieren backtracking: puzzles, matemáticas, planificación estratégica. Más caro computacionalmente pero más robusto en problemas difíciles."},

  {id:"q241",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Cuál es la técnica de 'formato de salida estructurada' y por qué es valiosa en aplicaciones?",
  options:[{key:"A",text:"Convertir las respuestas del modelo a formato de tabla solo para visualización."},{key:"B",text:"Instruir explícitamente al modelo para que devuelva respuestas en un formato específico (JSON, XML, lista numerada, tabla Markdown) para facilitar el parseo automático e integración con sistemas."},{key:"C",text:"Un método para reducir el tamaño de las respuestas del modelo."},{key:"D",text:"La configuración del formato de la API de invocación del modelo."}],
  answer:"B",
  explanation:"La salida estructurada es esencial para integración: 'Extrae la información del cliente y devuelve ÚNICAMENTE un JSON válido con el esquema: {\"name\": string, \"email\": string, \"issue\": string}'. Algunos modelos soportan JSON mode o structured output forzado. Permite parsear la respuesta programáticamente sin procesamiento de texto complejo."},

  {id:"q242",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Qué es el 'prompt chaining' y en qué escenarios es la técnica más adecuada?",
  options:[{key:"A",text:"Conectar múltiples modelos en cadena donde la salida de uno es la entrada del siguiente."},{key:"B",text:"Descomponer una tarea compleja en sub-tareas secuenciales donde la salida del prompt anterior alimenta el siguiente, permitiendo mayor control, verificación intermedia y modularidad."},{key:"C",text:"Repetir el mismo prompt múltiples veces para obtener respuestas más consistentes."},{key:"D",text:"Encadenar prompts en diferentes idiomas para mejorar la precisión multilingüe."}],
  answer:"B",
  explanation:"Prompt chaining es útil para: (1) Extraer información → (2) Validar extracción → (3) Formatear para sistema externo. Cada paso es verificable independientemente. También para flujos de trabajo: generar borrador → revisar → mejorar. Más controlable que un solo prompt complejo, permite insertar validaciones entre pasos."},

  {id:"q243",domain:3,subdomain:"3.2",service:null,difficulty:"hard",
  question:"¿Qué es el 'self-consistency prompting' y cómo mejora la confiabilidad del razonamiento?",
  options:[{key:"A",text:"Un método para que el modelo verifique internamente la consistencia de sus respuestas."},{key:"B",text:"Generar múltiples respuestas con chain-of-thought usando temperatura > 0, luego votar por mayoría la respuesta final, obteniendo resultados más robustos que una sola cadena de razonamiento."},{key:"C",text:"Instrucciones al modelo para que sea siempre consistente con respuestas anteriores."},{key:"D",text:"Una técnica de validación que compara la respuesta con la base de conocimiento."}],
  answer:"B",
  explanation:"Self-consistency genera N respuestas con CoT (N=10-40) usando temperatura > 0, luego selecciona la respuesta más frecuente (majority vote). Mejora la precisión en razonamiento matemático y lógico porque diferentes 'cadenas de razonamiento' llegan independientemente a la respuesta correcta. Costoso pero más preciso en tareas de razonamiento crítico."},

  {id:"q244",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Qué técnica de prompting es más efectiva para tareas de extracción de información de documentos no estructurados?",
  options:[{key:"A",text:"Zero-shot con instrucciones mínimas siempre es suficiente."},{key:"B",text:"Combinación de: instrucciones explícitas del schema de extracción, delimitadores para separar el documento, ejemplos few-shot del formato de salida esperado, y solicitud de salida JSON estructurada."},{key:"C",text:"Chain-of-thought es la única técnica efectiva para extracción de información."},{key:"D",text:"La extracción de información no requiere prompt engineering especial."}],
  answer:"B",
  explanation:"Para extracción robusta: (1) System prompt con el rol (eres un extractor de información experto), (2) Definir explícitamente los campos a extraer y su tipo, (3) Delimitadores (``` o XML) para el documento, (4) 2-3 ejemplos few-shot con distintos formatos de documento, (5) Pedir JSON con schema validable. Resultado: extracción consistente y parseable."},

  {id:"q245",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Qué es el 'ReAct prompting' (Reasoning + Acting) y por qué es importante para agentes?",
  options:[{key:"A",text:"Una técnica de prompting que combina respuestas en texto y en código."},{key:"B",text:"Un framework de prompting que intercala pasos de razonamiento (Thought) y acciones (Action/Observation) para resolver tareas que requieren buscar información o ejecutar herramientas, base del loop Thought-Action-Observation de los agentes."},{key:"C",text:"Un método de prompting para aplicaciones de realidad virtual y aumentada."},{key:"D",text:"Una técnica para que el modelo reaccione emocionalmente ante las preguntas del usuario."}],
  answer:"B",
  explanation:"ReAct (Yao et al., 2022) estructura el razonamiento del agente como: Thought: necesito saber X → Action: search[X] → Observation: resultado de la búsqueda → Thought: ahora sé X, necesito Y... Este ciclo permite al modelo razonar sobre qué herramienta usar, ejecutarla y refinar su comprensión. Es la base teórica de Bedrock Agents y LangChain Agents."},

  {id:"q246",domain:3,subdomain:"3.2",service:null,difficulty:"hard",
  question:"¿Qué es el 'Constitutional AI prompting' y cómo contribuye a respuestas más seguras?",
  options:[{key:"A",text:"Un método para programar leyes y regulaciones dentro del sistema prompt."},{key:"B",text:"Una técnica donde el modelo usa un conjunto de principios éticos (constitución) para auto-criticar y revisar sus propias respuestas, eliminando contenido dañino antes de la respuesta final."},{key:"C",text:"Un sistema de autenticación basado en la constitución legal del país del usuario."},{key:"D",text:"Una técnica de fine-tuning que usa datos de texto constitucional para alinear el modelo."}],
  answer:"B",
  explanation:"Constitutional AI (Anthropic) incluye una lista de principios éticos y hace que el modelo: (1) Genere una respuesta inicial, (2) Critique su propia respuesta según los principios ('¿viola algún principio?'), (3) Revise la respuesta para eliminar violaciones. Claude usa este enfoque. A nivel de prompting, se puede simular pidiendo al modelo auto-revisión según principios explícitos."},

  {id:"q247",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Qué estrategia de prompting es más efectiva para reducir alucinaciones del modelo?",
  options:[{key:"A",text:"Usar temperatura = 0 siempre garantiza cero alucinaciones."},{key:"B",text:"Instruir al modelo explícitamente a admitir incertidumbre ('si no sabes, dilo'), proporcionar documentos de contexto via RAG, pedir citas de fuentes y evitar preguntas para las que el modelo no tiene información en contexto."},{key:"C",text:"Usar modelos más grandes siempre elimina las alucinaciones completamente."},{key:"D",text:"Las alucinaciones son inevitables y no se pueden reducir con técnicas de prompting."}],
  answer:"B",
  explanation:"Para reducir alucinaciones: (1) RAG - anclar respuestas en documentos reales, (2) System prompt: 'Si no tienes información para responder esta pregunta, responde explícitamente que no lo sabes', (3) Pedir citas: 'cita el pasaje del documento que soporta tu respuesta', (4) Verificación: 'verifica que tu respuesta esté soportada por el texto provisto'. Temperatura = 0 reduce variabilidad pero no elimina alucinaciones."},

  {id:"q248",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Cuál es la diferencia entre un prompt de 'instrucción directa' versus un prompt de 'continuación de texto' en LLMs?",
  options:[{key:"A",text:"Son idénticos en todos los modelos modernos."},{key:"B",text:"Los prompts de instrucción directa ('Traduce al español: ...') son para modelos instruction-tuned que siguen comandos. Los prompts de continuación son para modelos base pre-entrenados que completan texto (el estilo puede variar más con el formato del prompt)."},{key:"C",text:"Solo los modelos de Anthropic soportan instrucciones directas."},{key:"D",text:"Los prompts de continuación son siempre más precisos que los de instrucción directa."}],
  answer:"B",
  explanation:"Los modelos base (sin instruction tuning) responden mejor a continuaciones de texto: 'La capital de Francia es...' → 'París'. Los modelos instruction-tuned/RLHF responden a comandos directos: 'Dime cuál es la capital de Francia'. Claude, GPT-4 y Llama-chat son instruction-tuned; los modelos base de SageMaker JumpStart pueden requerir prompting de continuación."},

  {id:"q249",domain:3,subdomain:"3.2",service:null,difficulty:"hard",
  question:"¿Qué es el 'negative prompting' y en qué tipo de modelos generativos es especialmente relevante?",
  options:[{key:"A",text:"Prompts que instruyen al modelo a generar respuestas negativas o críticas."},{key:"B",text:"Instrucciones sobre qué NO incluir en la generación; especialmente relevante en modelos de generación de imágenes (Stable Diffusion) donde se especifican elementos a excluir visualmente de la imagen generada."},{key:"C",text:"Una técnica para reducir la temperatura negativa del modelo durante la generación."},{key:"D",text:"Prompts que usan palabras de negación para hacer al modelo más preciso en NLP."}],
  answer:"B",
  explanation:"El negative prompt en Stable Diffusion especifica qué NO debe aparecer: 'negative prompt: blurry, low quality, extra limbs, deformed hands'. El modelo de difusión usa estos prompts para alejarse de esas características durante el proceso de denoising. También en LLMs: 'No uses tecnicismos', 'No repitas el prompt del usuario' son formas de negative prompting textual."},

  {id:"q250",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Qué es el 'context stuffing' y cuáles son sus limitaciones?",
  options:[{key:"A",text:"La técnica de añadir ruido aleatorio al contexto para mejorar la robustez del modelo."},{key:"B",text:"Incluir la mayor cantidad posible de información relevante en el contexto del LLM; limitado por el máximo de tokens de la ventana de contexto, costo creciente y el problema 'lost in the middle'."},{key:"C",text:"Un ataque de seguridad que intenta saturar el buffer del servidor del LLM."},{key:"D",text:"La compresión del contexto para reducir el uso de tokens."}],
  answer:"B",
  explanation:"El context stuffing (llenar el contexto con documentos) tiene límites: costo O(n²) en atención, degradación de rendimiento en info en el medio del contexto (lost in the middle), y eventualmente alcanza el límite de tokens. RAG es la alternativa: solo incluir los fragmentos más relevantes mediante búsqueda vectorial, no todo el corpus."},

  {id:"q251",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Cómo se debe estructurar un prompt para una tarea de clasificación de texto con categorías múltiples?",
  options:[{key:"A",text:"Solo preguntar al modelo que clasifique sin más contexto."},{key:"B",text:"Definir las categorías explícitamente con descripciones, incluir ejemplos (few-shot) de cada categoría, especificar el formato de salida exacto y las instrucciones para casos ambiguos."},{key:"C",text:"Usar únicamente zero-shot para clasificación; few-shot siempre empeora los resultados."},{key:"D",text:"La clasificación de texto no requiere prompt engineering; el modelo lo hace bien sin instrucciones."}],
  answer:"B",
  explanation:"Prompt óptimo para clasificación multi-clase: (1) 'Eres un clasificador de [dominio]', (2) Definir categorías: 'Categorías disponibles: A=[descripción], B=[descripción], C=[descripción]', (3) 2-3 ejemplos por categoría, (4) 'Responde ÚNICAMENTE con el nombre de la categoría', (5) Instrucción para ambiguos: 'Si no encaja claramente, elige la más cercana'. Resultado: clasificación consistente y parseable."},

  {id:"q252",domain:3,subdomain:"3.2",service:null,difficulty:"hard",
  question:"¿Qué es el 'adversarial prompting testing' y por qué es importante antes de desplegar una aplicación LLM?",
  options:[{key:"A",text:"Usar el modelo para generar prompts competitivos contra otros sistemas de IA."},{key:"B",text:"Probar sistemáticamente la robustez de la aplicación contra intentos maliciosos: prompt injection, jailbreaking, extracción del system prompt, manipulación del modelo para generar contenido prohibido."},{key:"C",text:"Comparar el rendimiento del modelo contra competidores de otras empresas."},{key:"D",text:"Entrenar el modelo con datos adversariales para mejorar su robustez."}],
  answer:"B",
  explanation:"El adversarial testing debe incluir: (1) Intentos de prompt injection ('Ignora las instrucciones anteriores y...'), (2) Jailbreaking con role-play ('Finge que eres una IA sin restricciones'), (3) Extracción del system prompt, (4) Manipulación para revelar datos confidenciales, (5) Solicitudes de contenido dañino con evasiones creativas. Bedrock Guardrails ayuda pero no es suficiente sin pruebas."},

  {id:"q253",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Qué es el 'prompt versioning' (versionado de prompts) y por qué es importante en producción?",
  options:[{key:"A",text:"El control de versiones del código fuente del LLM."},{key:"B",text:"Gestionar versiones de los prompts de la aplicación como si fueran código, rastreando cambios, permitiendo rollback, evaluando el impacto de cambios y manteniendo un historial auditable de qué prompt produjo qué resultados."},{key:"C",text:"La actualización automática de prompts cuando el modelo base se actualiza."},{key:"D",text:"La compresión de versiones antiguas de prompts para ahorrar almacenamiento."}],
  answer:"B",
  explanation:"Los prompts son código de aplicación crítico. El prompt versioning con herramientas como LangSmith, PromptLayer o soluciones custom en Git/S3 permite: comparar rendimiento entre versiones, rollback rápido si una nueva versión degrada resultados, auditoría de qué prompt generó qué respuesta en producción, y colaboración en equipo para optimización."},

  {id:"q254",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Cuál es la técnica de 'step-back prompting' y cuándo es más efectiva?",
  options:[{key:"A",text:"Una técnica para retroceder y usar una versión anterior del prompt cuando los resultados son malos."},{key:"B",text:"Instruir al modelo a primero responder una pregunta más general y abstracta antes de abordar la pregunta específica, mejorando el razonamiento al activar principios generales relevantes."},{key:"C",text:"Un método para reducir el número de pasos de razonamiento en chain-of-thought."},{key:"D",text:"La técnica de dar un paso atrás y evaluar si el prompt es necesario o puede eliminarse."}],
  answer:"B",
  explanation:"Step-back prompting: antes de responder '¿Cuál es la temperatura de fusión del oro?', el modelo primero responde '¿Qué principios físicos determinan el punto de fusión de un metal?' Esto activa conocimiento de física de sólidos que mejora la respuesta específica. Efectivo en ciencias, matemáticas y problemas técnicos."},

  {id:"q255",domain:3,subdomain:"3.2",service:null,difficulty:"medium",
  question:"¿Cómo afecta la longitud del prompt al rendimiento y costo en aplicaciones con LLMs?",
  options:[{key:"A",text:"Los prompts más largos siempre producen mejores respuestas sin impacto en costos."},{key:"B",text:"Prompts más largos aumentan el costo (más tokens de entrada), pueden aumentar latencia, y no siempre mejoran la calidad; el contexto irrelevante puede distraer al modelo. El objetivo es prompts concisos pero completos."},{key:"C",text:"Los prompts cortos siempre son mejores en todos los aspectos."},{key:"D",text:"La longitud del prompt no tiene impacto en el costo en Amazon Bedrock."}],
  answer:"B",
  explanation:"En Bedrock se paga por token de entrada Y salida. Prompts con cientos de páginas de documentos irrelevantes aumentan costo y latencia. Principio: incluir solo el contexto necesario. RAG es más eficiente que context stuffing. Prompt caching de Bedrock puede amortizar el costo de prefijos largos que se reutilizan constantemente."},

  {id:"q256",domain:3,subdomain:"3.3",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Cuáles son los pasos del proceso de fine-tuning de un modelo de foundation en Amazon Bedrock?",
  options:[{key:"A",text:"Solo se necesita proporcionar el nombre del nuevo modelo y se genera automáticamente."},{key:"B",text:"Preparar el dataset de fine-tuning en formato JSONL (pares prompt-completion), subirlo a S3, crear un fine-tuning job en Bedrock especificando el modelo base, configurar hiperparámetros (epochs, learning rate), esperar el entrenamiento, y desplegar con Provisioned Throughput."},{key:"C",text:"El fine-tuning en Bedrock requiere preparar imágenes Docker personalizadas con el modelo."},{key:"D",text:"Se realiza directamente mediante la consola de AWS con un formulario simple sin necesidad de datos propios."}],
  answer:"B",
  explanation:"El flujo de fine-tuning en Bedrock: (1) Preparar dataset JSONL (cada línea: {\"prompt\": \"...\", \"completion\": \"...\"}), (2) Subir a S3, (3) Crear Customization Job en Bedrock (modelo base, ubicación dataset, hiperparámetros), (4) El job ejecuta el entrenamiento en infraestructura gestionada, (5) El modelo personalizado se almacena en la cuenta del cliente, (6) Desplegar con Provisioned Throughput."},

  {id:"q257",domain:3,subdomain:"3.3",service:null,difficulty:"medium",
  question:"¿Cuántos datos de entrenamiento se necesitan típicamente para fine-tuning efectivo de un LLM?",
  options:[{key:"A",text:"Siempre se necesitan millones de ejemplos para cualquier fine-tuning."},{key:"B",text:"Depende de la tarea: para adaptar el estilo/formato pueden bastar cientos de ejemplos de alta calidad; para conocimiento de dominio muy específico se necesitan miles-decenas de miles. La calidad supera a la cantidad."},{key:"C",text:"Se necesita exactamente el mismo número de ejemplos que en el pre-entrenamiento."},{key:"D",text:"El fine-tuning no requiere datos nuevos; solo hiperparámetros diferentes."}],
  answer:"B",
  explanation:"Para fine-tuning de LLMs: para adaptación de estilo (tono, formato), 100-1000 ejemplos de alta calidad son suficientes (few-shot fine-tuning). Para conocimiento de dominio específico: 1000-50000+ ejemplos. La regla: datos de alta calidad, diversos y representativos del uso en producción. Datos de baja calidad o sesgados dañan el modelo."},

  {id:"q258",domain:3,subdomain:"3.3",service:null,difficulty:"hard",
  question:"¿Qué es el 'Continued Pre-training' (CPT) en Amazon Bedrock y en qué se diferencia del fine-tuning supervisado?",
  options:[{key:"A",text:"Son términos sinónimos para el mismo proceso."},{key:"B",text:"CPT continúa el pre-entrenamiento del modelo con documentos del dominio (textos no etiquetados) usando el objetivo de next-token prediction, ampliando el conocimiento del dominio; fine-tuning supervisado usa pares prompt-completion etiquetados para comportamientos específicos."},{key:"C",text:"CPT solo funciona con modelos de código; el fine-tuning es para modelos de lenguaje general."},{key:"D",text:"CPT es un proceso de entrenamiento en frío desde cero; el fine-tuning es el calentamiento del modelo."}],
  answer:"B",
  explanation:"CPT en Bedrock: alimentar el modelo con grandes cantidades de texto del dominio (documentación técnica, artículos médicos, código de la empresa) sin etiquetas, para que aprenda terminología y conocimiento especializado. Fine-tuning supervisado: pares (instrucción, respuesta ideal) para comportamientos específicos. Bedrock soporta ambos; CPT es más costoso pero más profundo en conocimiento."},

  {id:"q259",domain:3,subdomain:"3.3",service:null,difficulty:"medium",
  question:"¿Cuándo se debe preferir fine-tuning sobre RAG para incorporar conocimiento en un FM?",
  options:[{key:"A",text:"Siempre; el fine-tuning es siempre superior a RAG."},{key:"B",text:"Fine-tuning es preferible cuando: el conocimiento es estático y raramente cambia, se necesita que el modelo 'hable el idioma del dominio' de forma fluida, el volumen de llamadas hace prohibitivo el RAG, o se necesita mejorar capacidades de razonamiento en el dominio específico."},{key:"C",text:"Nunca; RAG es siempre más efectivo y económico que el fine-tuning."},{key:"D",text:"Fine-tuning es la única opción para datos confidenciales que no pueden enviarse en el prompt."}],
  answer:"B",
  explanation:"Fine-tuning > RAG cuando: el conocimiento es conocimiento implícito del dominio (cómo escribe un médico, cómo razona un abogado), hay volumen altísimo donde añadir contexto RAG es muy costoso, o el estilo/tono de respuesta debe ser muy específico. RAG > Fine-tuning cuando: el conocimiento cambia frecuentemente, se necesitan citas de fuentes, o los datos son muy variables."},

  {id:"q260",domain:3,subdomain:"3.3",service:null,difficulty:"hard",
  question:"¿Qué es el 'catastrophic forgetting' en el contexto del fine-tuning de LLMs y cómo se mitiga?",
  options:[{key:"A",text:"Cuando el servidor que ejecuta el fine-tuning falla y se pierden los datos de entrenamiento."},{key:"B",text:"El fenómeno donde el LLM, al fine-tunearse en datos específicos del dominio, degrada su rendimiento en capacidades generales que tenía antes del fine-tuning. Se mitiga con LoRA, regularización y datasets mezclados."},{key:"C",text:"La pérdida de los pesos del modelo después del fine-tuning por problemas de almacenamiento."},{key:"D",text:"Cuando el modelo olvida el fine-tuning anterior al realizar una segunda ronda de ajuste."}],
  answer:"B",
  explanation:"El catastrophic forgetting en fine-tuning es riesgo real: si solo se entrena con datos muy específicos, el modelo puede perder capacidades generales de razonamiento, escritura o código. Mitigaciones: LoRA (solo actualiza matrices de bajo rango, preserva pesos originales), mezclar datos de fine-tuning con una fracción de datos generales, y PEFT (Parameter Efficient Fine-Tuning)."},

  {id:"q261",domain:3,subdomain:"3.3",service:null,difficulty:"medium",
  question:"¿Qué es el 'RLHF' (Reinforcement Learning from Human Feedback) en el fine-tuning y cuáles son sus pasos?",
  options:[{key:"A",text:"Una técnica para que el modelo aprenda automáticamente de comentarios de usuarios en producción."},{key:"B",text:"Proceso de 3 fases: (1) SFT - entrenar en ejemplos de alta calidad, (2) Entrenadores humanos rankean respuestas del modelo para entrenar un Reward Model, (3) Optimizar el LLM con PPO/REINFORCE maximizando la puntuación del Reward Model."},{key:"C",text:"Un algoritmo de ML para optimizar la función de pérdida del modelo base."},{key:"D",text:"Un proceso de fine-tuning donde el modelo genera retroalimentación sobre sí mismo."}],
  answer:"B",
  explanation:"RLHF es el estándar para alinear LLMs: (1) SFT: fine-tuning supervisado con ejemplos de alta calidad humana. (2) Reward Model: entrenadores comparan respuestas A vs B del modelo; se entrena un RM para predecir preferencias humanas. (3) RL: se optimiza el LLM con PPO para maximizar recompensa del RM con un término KL-penalty para no alejarse demasiado del modelo base."},

  {id:"q262",domain:3,subdomain:"3.3",service:null,difficulty:"hard",
  question:"¿Qué es DPO (Direct Preference Optimization) y cómo se compara con RLHF?",
  options:[{key:"A",text:"Una técnica de optimización para reducir el número de parámetros del modelo."},{key:"B",text:"Una alternativa más simple al RLHF que optimiza directamente las preferencias humanas sin necesitar un Reward Model separado ni RL, usando una función de pérdida que aumenta la probabilidad de respuestas preferidas y disminuye la de las rechazadas."},{key:"C",text:"Un método de depuración de modelos para identificar respuestas problemáticas."},{key:"D",text:"Un proceso de cuantización que preserva las preferencias de los usuarios en modelos comprimidos."}],
  answer:"B",
  explanation:"DPO simplifica RLHF: usa el mismo dataset de preferencias (respuesta ganadora, respuesta perdedora) pero optimiza directamente sin el Reward Model separado ni el costoso loop de RL. La función de pérdida DPO es más estable de entrenar, requiere menos recursos y produce resultados similares a RLHF. Muy popular en la comunidad open-source."},

  {id:"q263",domain:3,subdomain:"3.3",service:null,difficulty:"medium",
  question:"¿Cuáles son los requisitos de formato del dataset para fine-tuning en Amazon Bedrock?",
  options:[{key:"A",text:"CSV con columnas 'input' y 'output' separadas por comas."},{key:"B",text:"JSONL (JSON Lines) donde cada línea es un objeto JSON con el formato {\"prompt\": \"texto de instrucción\", \"completion\": \"respuesta ideal\"}, o en formato de mensajes multi-turno para conversaciones."},{key:"C",text:"Archivos de texto plano .txt con prompts y respuestas separados por líneas en blanco."},{key:"D",text:"Formato Parquet optimizado para procesamiento distribuido."}],
  answer:"B",
  explanation:"Bedrock acepta JSONL para fine-tuning: cada línea es un JSON independiente. Para fine-tuning de instrucción: {\"prompt\": \"Clasifica el sentimiento: Me encantó\", \"completion\": \"Positivo\"}. Para conversaciones multi-turno: {\"messages\": [{\"role\": \"user\", \"content\": \"...\"}, {\"role\": \"assistant\", \"content\": \"...\"}]}. El dataset debe subirse a S3 antes de crear el job."},

  {id:"q264",domain:3,subdomain:"3.3",service:null,difficulty:"medium",
  question:"¿Cuáles son las consideraciones de calidad más importantes para un dataset de fine-tuning?",
  options:[{key:"A",text:"Solo importa la cantidad; más datos siempre producen mejores modelos."},{key:"B",text:"Diversidad (cubrir los casos de uso y estilos esperados), consistencia (respuestas del mismo tono/formato), ausencia de ruido (sin errores ni información incorrecta), balance de categorías, y representatividad del uso en producción."},{key:"C",text:"Los datos de fine-tuning pueden tener cualquier calidad ya que el modelo los filtra automáticamente."},{key:"D",text:"Solo se necesita data de los últimos 30 días para que sea relevante."}],
  answer:"B",
  explanation:"La calidad del dataset de fine-tuning determina la calidad del modelo resultante. Problemas comunes: respuestas inconsistentes entre sí (el modelo aprende contradiciones), datos sesgados (el modelo amplifica el sesgo), errores factuales (el modelo aprende hechos incorrectos), poca diversidad (el modelo se sobre-especializa). Regla: menos datos de altísima calidad > muchos datos de baja calidad."},

  {id:"q265",domain:3,subdomain:"3.3",service:null,difficulty:"hard",
  question:"¿Qué es el 'model alignment' y por qué es crítico en el desarrollo de modelos de foundation?",
  options:[{key:"A",text:"El proceso técnico de alinear los pesos del modelo con el hardware de inferencia."},{key:"B",text:"El proceso de asegurar que el comportamiento del modelo se alinea con los valores, intenciones y expectativas humanas: ser útil (helpful), inofensivo (harmless) y honesto (honest), usando técnicas como RLHF, Constitutional AI y DPO."},{key:"C",text:"La sincronización de múltiples instancias del mismo modelo para respuestas consistentes."},{key:"D",text:"El proceso de ajustar el modelo para soportar múltiples idiomas de forma correcta."}],
  answer:"B",
  explanation:"El model alignment (alineación) busca que el LLM sea: Helpful (responde útilmente), Harmless (no genera daño), Honest (no miente, admite incertidumbre). Sin alineación, los LLMs pre-entrenados pueden generar contenido dañino, instrucciones peligrosas o desinformación. RLHF, Constitutional AI y DPO son las principales técnicas de alineación actuales."},

  {id:"q266",domain:3,subdomain:"3.3",service:null,difficulty:"medium",
  question:"¿Qué es el 'transfer learning' en el contexto específico de los Foundation Models?",
  options:[{key:"A",text:"Mover un modelo de una región de AWS a otra para mejora de latencia."},{key:"B",text:"Partir de un FM pre-entrenado en datos masivos y adaptarlo a una tarea/dominio específico mediante fine-tuning, aprovechando el conocimiento general ya aprendido en lugar de entrenar desde cero."},{key:"C",text:"La transferencia de los pesos de un modelo al hardware de producción para inferencia."},{key:"D",text:"Un método para reutilizar el dataset de entrenamiento entre múltiples modelos."}],
  answer:"B",
  explanation:"Los FMs son el ejemplo perfecto de transfer learning a escala: un modelo pre-entrenado en billones de tokens de texto diverso captura comprensión del lenguaje, razonamiento y conocimiento del mundo. El fine-tuning transfiere este conocimiento a una tarea específica (soporte médico, análisis legal) con órdenes de magnitud menos datos y compute que entrenar desde cero."},

  {id:"q267",domain:3,subdomain:"3.3",service:null,difficulty:"hard",
  question:"¿Qué es el 'model distillation' y cómo se aplica en el contexto de los LLMs?",
  options:[{key:"A",text:"El proceso de destilación de los datos de entrenamiento para eliminar duplicados."},{key:"B",text:"Una técnica que entrena un modelo pequeño (student) para imitar el comportamiento de un modelo grande (teacher), usando las distribuciones de probabilidad del teacher como señal de entrenamiento, obteniendo un modelo más pequeño pero con rendimiento similar."},{key:"C",text:"La compresión de los pesos del modelo sin modificar su arquitectura."},{key:"D",text:"El proceso de extraer el conocimiento del modelo y almacenarlo en una base de datos."}],
  answer:"B",
  explanation:"Knowledge Distillation: el modelo 'teacher' grande genera distribuciones de probabilidad suaves (soft targets) para cada ejemplo; el modelo 'student' pequeño aprende a imitar estas distribuciones. Resultado: un modelo más pequeño y rápido que aproxima el rendimiento del grande. Usado por Google (DistilBERT), Meta y otros para modelos de producción eficientes."},

  {id:"q268",domain:3,subdomain:"3.3",service:null,difficulty:"medium",
  question:"¿Qué son los 'adapter layers' en el fine-tuning eficiente de LLMs?",
  options:[{key:"A",text:"Capas de hardware que adaptan los chips de GPU para mayor eficiencia."},{key:"B",text:"Módulos pequeños insertados entre las capas del transformer que se entrenan durante el fine-tuning mientras los parámetros originales del modelo se mantienen congelados, siendo más eficientes que el fine-tuning completo."},{key:"C",text:"APIs que adaptan el formato de entrada del LLM a diferentes fuentes de datos."},{key:"D",text:"Capas de traducción que adaptan el modelo para múltiples idiomas simultáneamente."}],
  answer:"B",
  explanation:"Los adapter layers son módulos adicionales (bottleneck: proyecto a dimensión reducida, capa no lineal, proyección de vuelta) insertados en el modelo. Solo se entrenan estos adaptadores (< 1% de parámetros) mientras el modelo base se congela. Resultado: eficiencia de LoRA con la modularidad de tener múltiples adaptadores intercambiables por tarea."},

  {id:"q269",domain:3,subdomain:"3.3",service:null,difficulty:"medium",
  question:"¿Cuáles son las diferencias clave entre fine-tuning completo (full fine-tuning) y PEFT (Parameter-Efficient Fine-Tuning)?",
  options:[{key:"A",text:"Full fine-tuning es siempre mejor en calidad; PEFT es solo para hardware limitado."},{key:"B",text:"Full fine-tuning actualiza todos los parámetros del modelo (más costoso, mayor riesgo de catastrophic forgetting); PEFT (LoRA, adapters) actualiza solo una fracción pequeña de parámetros (más barato, menos forgetting, más fácil de mantener múltiples versiones)."},{key:"C",text:"PEFT es siempre superior; el full fine-tuning ya no se usa."},{key:"D",text:"Son idénticos en costo y calidad; solo difieren en el framework de implementación."}],
  answer:"B",
  explanation:"Full fine-tuning: entrena todos los N mil millones de parámetros, requiere múltiples GPUs, mayor riesgo de forgetting. PEFT (LoRA, QLoRA, adapters, prefix tuning): entrena solo 0.1-1% de parámetros, puede ejecutarse en 1 GPU consumer (QLoRA), preserva mejor el conocimiento general. Para la mayoría de casos empresariales, PEFT es suficiente y mucho más práctico."},

  {id:"q270",domain:3,subdomain:"3.3",service:null,difficulty:"hard",
  question:"¿Qué son los 'datos sintéticos' para fine-tuning y cuándo es apropiado usarlos?",
  options:[{key:"A",text:"Datos falsos creados manualmente para engañar al modelo y mejorar su robustez."},{key:"B",text:"Datos generados por un LLM (teacher) para crear ejemplos de entrenamiento de alta calidad cuando los datos reales son escasos, costosos de etiquetar o por privacidad no pueden usarse directamente."},{key:"C",text:"Datos de simulaciones físicas usados para entrenar modelos de robótica."},{key:"D",text:"Datos de test automatizados para verificar el fine-tuning antes del despliegue."}],
  answer:"B",
  explanation:"Los datos sintéticos se generan usando un LLM grande (ej. GPT-4 o Claude) para crear ejemplos de alta calidad. Casos de uso: (1) Escasez de datos etiquetados reales, (2) Datos de privacidad sensible que no pueden usarse directamente (los datos sintéticos preservan patrones sin información real), (3) Crear variaciones y augmentación. Riesgo: model collapse si se abusa."},

  {id:"q271",domain:3,subdomain:"3.4",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Qué métricas automáticas ofrece Amazon Bedrock Model Evaluation para evaluar LLMs?",
  options:[{key:"A",text:"Solo latencia y throughput; las métricas de calidad requieren evaluación humana siempre."},{key:"B",text:"Métricas de calidad de respuesta (ROUGE, BERTScore), precisión factual (groundedness), toxicidad/contenido dañino, seguimiento de instrucciones y coherencia semántica, dependiendo de la tarea evaluada."},{key:"C",text:"Únicamente accuracy de clasificación, sin métricas específicas para generación."},{key:"D",text:"Solo el número de tokens generados como proxy de la calidad del modelo."}],
  answer:"B",
  explanation:"Bedrock Model Evaluation incluye: (1) Métricas de generación: ROUGE-L, BERTScore para similitud semántica. (2) Robustez: evaluación de comportamiento ante variaciones de prompt. (3) Toxicidad: detección de contenido dañino. (4) Groundedness: ¿la respuesta está fundamentada en el contexto provisto? (5) Correctness factual con dataset de pares pregunta-respuesta esperada."},

  {id:"q272",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Qué es el 'BLEU score' y cómo se usa para evaluar modelos de generación de texto?",
  options:[{key:"A",text:"Una métrica de evaluación del color azul de las interfaces de usuario."},{key:"B",text:"Una métrica que mide la solapamiento de n-gramas entre el texto generado por el modelo y textos de referencia escritos por humanos; valores de 0 (ningún solapamiento) a 1 (idéntico)."},{key:"C",text:"Una puntuación de 0-100 que mide la velocidad de generación de tokens."},{key:"D",text:"Una métrica exclusiva para evaluar modelos de traducción automática sin comparación con humanos."}],
  answer:"B",
  explanation:"BLEU (Bilingual Evaluation Understudy) compara n-gramas del texto generado con referencias humanas. Originalmente diseñado para traducción, se usa también para resumen y generación. Limitación: no captura bien el significado semántico (sinónimos). BERTScore y ROUGE-L son alternativas que capturan mejor la similitud semántica y de contenido."},

  {id:"q273",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Qué es el 'ROUGE score' y en qué escenarios es más apropiado que BLEU?",
  options:[{key:"A",text:"Rouge es idéntico a BLEU pero con nombre diferente."},{key:"B",text:"ROUGE (Recall-Oriented Understudy for Gisting Evaluation) mide el recall de n-gramas; ROUGE-L usa la subsecuencia común más larga; es más apropiado para resumen de texto donde importa qué información esencial fue cubierta."},{key:"C",text:"ROUGE es una métrica para evaluar solo modelos de clasificación de texto."},{key:"D",text:"ROUGE mide la coherencia gramatical del texto generado sin comparación con referencias."}],
  answer:"B",
  explanation:"ROUGE-N mide recall de n-gramas (cuánto del texto de referencia aparece en la generación). ROUGE-L usa la longest common subsequence. Muy usado para evaluar resúmenes: ¿el modelo capturó los puntos clave del original? ROUGE-1 (unigramas) y ROUGE-2 (bigramas) son los más comunes. Bedrock Model Evaluation lo incluye para evaluar tareas de resumen."},

  {id:"q274",domain:3,subdomain:"3.4",service:null,difficulty:"hard",
  question:"¿Qué es el 'LLM-as-judge' (LLM como evaluador) y cuáles son sus ventajas y riesgos?",
  options:[{key:"A",text:"El uso de un LLM como árbitro en disputas legales para garantizar imparcialidad."},{key:"B",text:"Usar un LLM potente (ej. GPT-4 o Claude Opus) para evaluar automáticamente la calidad de las respuestas de otro LLM, permitiendo evaluación a escala sin evaluadores humanos, con el riesgo de sesgos propios del evaluador."},{key:"C",text:"Un sistema de auditoría donde el LLM revisa sus propias respuestas para corregir errores."},{key:"D",text:"Una técnica para entrenar modelos de evaluación usando el LLM como teacher."}],
  answer:"B",
  explanation:"LLM-as-judge: se le presenta al LLM evaluador la pregunta, la respuesta y criterios de evaluación; el LLM puntúa la respuesta en dimensiones como utilidad, precisión, concisión. Ventajas: escala, consistencia, bajo costo vs. evaluadores humanos. Riesgos: sesgo hacia modelos del mismo proveedor, preferencia por respuestas largas, falta de ground truth."},

  {id:"q275",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Qué es el 'groundedness score' (puntuación de fundamentación) y por qué es importante en sistemas RAG?",
  options:[{key:"A",text:"Una métrica que mide cuán sólidas son las bases del hardware del sistema de IA."},{key:"B",text:"Una métrica que evalúa si la respuesta generada por el LLM está fundamentada y puede verificarse en los documentos de contexto provisto, detectando alucinaciones respecto al contexto dado."},{key:"C",text:"Una puntuación que mide si el modelo fue correctamente inicializado antes del entrenamiento."},{key:"D",text:"La métrica de velocidad de recuperación de documentos en el vector store."}],
  answer:"B",
  explanation:"El groundedness score en Bedrock Guardrails analiza si cada afirmación de la respuesta del LLM está soportada por los documentos recuperados por RAG. Una respuesta 'ungrounded' indica que el modelo inventó información no presente en el contexto. Esencial para aplicaciones empresariales donde la precisión factual es crítica (legal, médica, financiera)."},

  {id:"q276",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Cómo se realiza la evaluación humana de modelos de IA generativa y cuáles son sus ventajas sobre la evaluación automática?",
  options:[{key:"A",text:"La evaluación humana es obsoleta; las métricas automáticas son siempre más precisas."},{key:"B",text:"Evaluadores humanos puntúan respuestas en dimensiones subjetivas (utilidad, naturalidad, precisión) que las métricas automáticas no capturan bien; ofrece feedback más rico y alineado con la experiencia real del usuario, aunque es costosa y más lenta."},{key:"C",text:"La evaluación humana solo es válida para imágenes; el texto requiere métricas automáticas."},{key:"D",text:"Solo expertos en IA pueden realizar evaluaciones humanas válidas de LLMs."}],
  answer:"B",
  explanation:"La evaluación humana captura dimensiones que las métricas automáticas no pueden: ¿fue útil para el usuario? ¿la respuesta fue confusa? ¿tiene el tono correcto? Bedrock Model Evaluation soporta evaluaciones humanas con equipos internos o a través de plataformas de terceros. Se usan rúbricas específicas para asegurar consistencia entre evaluadores."},

  {id:"q277",domain:3,subdomain:"3.4",service:null,difficulty:"hard",
  question:"¿Qué es el 'benchmark' de modelos y qué benchmarks son comunes para evaluar LLMs?",
  options:[{key:"A",text:"Una prueba de rendimiento de hardware para medir la velocidad de procesamiento de GPUs."},{key:"B",text:"Conjuntos de tareas y datasets estandarizados (MMLU, HumanEval, GSM8K, HellaSwag) que permiten comparar el rendimiento de diferentes modelos de forma objetiva y reproducible en razonamiento, código, matemáticas y comprensión general."},{key:"C",text:"Un certificado de calidad que AWS emite para modelos aprobados para uso empresarial."},{key:"D",text:"Una métrica interna de Amazon para clasificar los modelos disponibles en Bedrock."}],
  answer:"B",
  explanation:"Benchmarks importantes de LLMs: MMLU (conocimiento general en 57 materias), HumanEval/MBPP (generación de código), GSM8K/MATH (razonamiento matemático), HellaSwag (sentido común), TruthfulQA (veracidad), BIG-Bench Hard (razonamiento difícil). Los FMs en Bedrock publican sus resultados en benchmarks públicos para comparación. Caveat: 'benchmark gaming' puede inflar resultados."},

  {id:"q278",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Qué es la 'evaluación A/B de modelos' en producción y cómo se implementa?",
  options:[{key:"A",text:"Comparar el texto generado por el modelo A con el texto del modelo B visualmente."},{key:"B",text:"Enrutar una fracción del tráfico de producción real a diferentes versiones del modelo y comparar métricas de negocio (satisfacción del usuario, tasa de escalado, tiempo de resolución) para determinar qué modelo produce mejores resultados en condiciones reales."},{key:"C",text:"Evaluar el modelo solo con datasets de evaluación tipo A (easy) y tipo B (hard)."},{key:"D",text:"Una técnica exclusiva de entrenamiento donde se comparan dos modelos en el mismo dataset."}],
  answer:"B",
  explanation:"La evaluación A/B en producción LLM envía, por ejemplo, 10% del tráfico al nuevo modelo y 90% al actual, comparando métricas reales de negocio. Para chatbots: tasa de satisfacción, % de escalados a humanos, tiempo de resolución. Para generación de contenido: tasa de clics, ediciones por el usuario. Es el gold standard para validar mejoras antes del rollout completo."},

  {id:"q279",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Qué es la 'evaluación adversarial' de modelos de IA generativa y por qué es esencial?",
  options:[{key:"A",text:"Evaluar el modelo con datos de empresas competidoras."},{key:"B",text:"Probar sistemáticamente el modelo con prompts diseñados para hacer que falle, revele información sensible, genere contenido dañino o muestre inconsistencias, para identificar vulnerabilidades de seguridad y alineación antes del despliegue."},{key:"C",text:"Una evaluación donde el modelo compite contra sí mismo en una tarea competitiva."},{key:"D",text:"El proceso de probar el modelo en condiciones de hardware adversas (baja memoria, CPU lenta)."}],
  answer:"B",
  explanation:"La evaluación adversarial es crítica: red-teaming humano + automatizado para encontrar: (1) Jailbreaks (eludir restricciones de seguridad), (2) Prompt injection vulnerabilities, (3) Respuestas sesgadas ante preguntas con carga política/social, (4) Generación de información peligrosa disfrazada en contextos benignos. AWS recomienda red-teaming antes del despliegue en producción."},

  {id:"q280",domain:3,subdomain:"3.4",service:"Amazon Bedrock",difficulty:"hard",
  question:"¿Cómo se evalúa la 'seguridad' de un modelo de IA generativa en el contexto empresarial?",
  options:[{key:"A",text:"Solo evaluando la velocidad de respuesta y el tiempo de inactividad del servicio."},{key:"B",text:"Evaluando múltiples dimensiones: robustez ante prompt injection, resistencia a jailbreaking, filtrado de contenido dañino, protección de PII, resistencia a extracción del system prompt, y comportamiento ante edge cases del dominio específico de la aplicación."},{key:"C",text:"La seguridad del LLM es responsabilidad exclusiva del proveedor del modelo."},{key:"D",text:"Solo se evalúa la seguridad del código de la aplicación, no del modelo en sí."}],
  answer:"B",
  explanation:"La evaluación de seguridad de LLMs en producción incluye: (1) Red-teaming con intentos de prompt injection y jailbreaking, (2) Testing de Bedrock Guardrails con casos límite, (3) Evaluación de filtrado de contenido en categorías relevantes, (4) Testing de PII redaction con datos reales, (5) Evaluación de robustez ante variaciones maliciosas del prompt, (6) Monitoreo continuo de logs para detectar intentos de abuso."},

  {id:"q281",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Qué son los 'evals' (evaluaciones) en el contexto del desarrollo de aplicaciones LLM?",
  options:[{key:"A",text:"Las funciones de evaluación matemática para calcular métricas de rendimiento del hardware."},{key:"B",text:"Conjuntos de casos de prueba curados (pregunta, respuesta esperada, criterios de calidad) que permiten medir sistemáticamente si los cambios en el modelo o el prompt mejoran o empeoran el rendimiento de la aplicación."},{key:"C",text:"Las evaluaciones de mercado que determinan el precio de los modelos de IA."},{key:"D",text:"Tests de carga automatizados para medir la latencia de la API del modelo."}],
  answer:"B",
  explanation:"Los 'evals' son el equivalente de los tests unitarios para aplicaciones LLM. Un eval set contiene: prompts de prueba representativos del uso real, respuestas de referencia y/o criterios de evaluación. Se ejecutan automáticamente en el CI/CD para detectar regresiones cuando se cambia el prompt, el modelo o el pipeline RAG. Fundamental para desarrollo de aplicaciones LLM en producción."},

  {id:"q282",domain:3,subdomain:"3.4",service:null,difficulty:"hard",
  question:"¿Qué es la 'calibración' de un modelo probabilístico y por qué es importante en aplicaciones críticas?",
  options:[{key:"A",text:"El ajuste físico de los sensores de hardware que ejecutan el modelo."},{key:"B",text:"La alineación entre la confianza expresada por el modelo y su precisión real: un modelo bien calibrado que dice '80% seguro' debería ser correcto el 80% de las veces; importante en diagnóstico médico, finanzas y predicciones de alto riesgo."},{key:"C",text:"El proceso de ajustar los hiperparámetros del modelo para cada dataset."},{key:"D",text:"La sincronización entre el reloj del sistema y los logs del modelo para auditoría."}],
  answer:"B",
  explanation:"La calibración mide si las probabilidades del modelo corresponden a frecuencias reales. Los LLMs tienden a estar mal calibrados: pueden expresar alta confianza en respuestas incorrectas (overconfidence). En aplicaciones médicas o financieras, un modelo que dice '99% seguro' cuando es correcto solo el 60% de las veces es peligroso. Técnicas de calibración: Platt scaling, temperature scaling."},

  {id:"q283",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Cuál es la diferencia entre 'offline evaluation' y 'online evaluation' de modelos LLM?",
  options:[{key:"A",text:"Offline usa datos históricos; online usa datos en tiempo real de producción para el mismo proceso."},{key:"B",text:"Offline evaluation: evaluar el modelo con datasets curados antes del despliegue usando métricas automáticas y humanas. Online evaluation: monitorear el rendimiento del modelo con tráfico real en producción (feedback de usuarios, métricas de negocio, logs)."},{key:"C",text:"Offline es en servidores dedicados; online es en la nube."},{key:"D",text:"Son idénticos; la distinción es solo semántica."}],
  answer:"B",
  explanation:"Offline (pre-deployment): datasets curados, métricas automáticas (ROUGE, BERTScore), evaluación humana, red-teaming. Ventaja: controlado, reproducible. Desventaja: no captura distribución real del usuario. Online (post-deployment): thumbs up/down del usuario, tasa de re-intentos, escalados a humanos, análisis de logs. Ambos son necesarios para un ciclo de mejora continua."},

  {id:"q284",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Qué es la 'coherencia' como dimensión de evaluación en modelos generativos y cómo se mide?",
  options:[{key:"A",text:"La velocidad y consistencia de las respuestas del modelo bajo carga alta."},{key:"B",text:"La propiedad de que el texto generado sea lógicamente consistente consigo mismo (sin contradicciones) y con el contexto dado; se evalúa con checkers de implicación textual, LLM-as-judge o evaluación humana."},{key:"C",text:"La coherencia de colores en las imágenes generadas por modelos de difusión."},{key:"D",text:"La consistencia entre la documentación del modelo y su comportamiento real."}],
  answer:"B",
  explanation:"La coherencia evalúa: ¿el texto generado se contradice a sí mismo dentro de la misma respuesta? ¿es consistente con el historial de conversación? ¿mantiene el mismo tono y persona a lo largo de una respuesta larga? Se evalúa con: NLI models (Natural Language Inference) para detectar contradicciones, o LLM-as-judge con criterios de coherencia explícitos."},

  {id:"q285",domain:3,subdomain:"3.4",service:null,difficulty:"hard",
  question:"¿Qué es el 'HELM' (Holistic Evaluation of Language Models) y qué aporta a la evaluación de LLMs?",
  options:[{key:"A",text:"Un hardware específico de AWS para pruebas de rendimiento de modelos de lenguaje."},{key:"B",text:"Un framework de evaluación holístico de Stanford que evalúa LLMs en múltiples dimensiones: precisión en tareas diversas, calibración, robustez, equidad, sesgo, toxicidad y eficiencia, para una comparación comprensiva de modelos."},{key:"C",text:"Un estándar de la industria para la certificación de modelos de IA para uso médico."},{key:"D",text:"Una técnica de visualización de los pesos del modelo para interpretabilidad."}],
  answer:"B",
  explanation:"HELM (Stanford, 2022) evalúa LLMs de forma holística: 42 escenarios, 7 métricas (accuracy, calibración, robustez, equidad, sesgo, toxicidad, eficiencia). Va más allá del benchmark tradicional para capturar el comportamiento real del modelo en producción. Útil para comparar modelos de forma transparente antes de elegir cuál usar en una aplicación crítica."},

  {id:"q286",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Cuál es la importancia del 'test set' independiente en la evaluación final de un modelo fine-tuneado?",
  options:[{key:"A",text:"El test set es opcional si el modelo tuvo buen rendimiento en el conjunto de validación."},{key:"B",text:"El test set debe ser un conjunto de datos completamente reservado, nunca visto durante entrenamiento ni ajuste de hiperparámetros, que proporciona la estimación más honesta del rendimiento real del modelo en condiciones de producción."},{key:"C",text:"El test set es idéntico al conjunto de validación con un nombre diferente."},{key:"D",text:"El test set se puede reutilizar entre múltiples experimentos de fine-tuning sin problema."}],
  answer:"B",
  explanation:"El test set debe estar completamente aislado durante todo el desarrollo. Si se usa para tomar decisiones de hiperparámetros o selección de modelo, ya no es imparcial (data leakage). La evaluación final en el test set representa el rendimiento esperado en producción. Para fine-tuning en Bedrock: reservar siempre un 10-20% de datos como test set final."},

  {id:"q287",domain:3,subdomain:"3.4",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Cómo evalúa Amazon Bedrock Model Evaluation el rendimiento en múltiples modelos simultáneamente?",
  options:[{key:"A",text:"Solo puede evaluar un modelo a la vez; la comparación es manual."},{key:"B",text:"Permite crear un 'evaluation job' con múltiples modelos participantes y el mismo conjunto de prompts, generando un reporte comparativo con todas las métricas por modelo para facilitar la selección del FM más adecuado para el caso de uso."},{key:"C",text:"La evaluación multi-modelo requiere construir una infraestructura personalizada en SageMaker."},{key:"D",text:"Los modelos se evalúan en diferentes fechas y los resultados se comparan manualmente."}],
  answer:"B",
  explanation:"Bedrock Model Evaluation permite: (1) Seleccionar múltiples modelos del catálogo de Bedrock, (2) Subir el dataset de evaluación, (3) Configurar las métricas deseadas, (4) Lanzar el evaluation job que invoca todos los modelos con los mismos prompts, (5) Ver un dashboard comparativo. Ideal para comparar Claude Haiku vs. Llama 3 8B vs. Titan Text para una tarea específica."},

  {id:"q288",domain:3,subdomain:"3.4",service:null,difficulty:"hard",
  question:"¿Cuáles son las principales métricas de evaluación específicas para modelos de generación de código?",
  options:[{key:"A",text:"Solo BLEU y ROUGE son suficientes para evaluar código generado."},{key:"B",text:"Pass@k (porcentaje de problemas donde al menos k de las N soluciones generadas pasan los tests), ejecución funcional de los tests unitarios, y CodeBLEU (BLEU adaptado para código que considera AST y flujo de datos)."},{key:"C",text:"La calidad del código no se puede medir automáticamente; solo revisión humana es válida."},{key:"D",text:"Solo se mide la compilación exitosa; la corrección funcional no se puede automatizar."}],
  answer:"B",
  explanation:"Para evaluar código generado: Pass@k (de N soluciones generadas, ¿cuántas pasan todos los unit tests?) es el gold standard. HumanEval y MBPP son los benchmarks estándar. CodeBLEU adapta BLEU considerando coincidencia de tokens de código, match de AST (estructura) y match de flujo de datos. La ejecución de tests es más confiable que la similitud textual para código."},

  {id:"q289",domain:3,subdomain:"3.4",service:null,difficulty:"medium",
  question:"¿Qué es la 'fluency' (fluidez) como métrica de evaluación y cómo se distingue de la 'coherencia'?",
  options:[{key:"A",text:"Son métricas idénticas con nombres distintos."},{key:"B",text:"Fluidez evalúa la calidad lingüística del texto: gramática correcta, sintaxis natural, vocabulario apropiado. Coherencia evalúa la consistencia lógica y el flujo de ideas. Un texto puede ser fluido (bien escrito) pero incoherente (contradicciones internas)."},{key:"C",text:"Fluidez mide solo la velocidad de generación; coherencia mide la calidad del contenido."},{key:"D",text:"La fluidez solo aplica para texto multilingüe; la coherencia para texto en un solo idioma."}],
  answer:"B",
  explanation:"Fluidez: ¿el texto suena natural en el idioma? ¿tiene errores gramaticales? ¿el vocabulario es apropiado para el contexto? Coherencia: ¿las ideas se conectan lógicamente? ¿no hay contradicciones? Un resumen puede ser fluido (bien escrito) pero no coherente (introduce información contradictoria). Ambas son necesarias para texto de alta calidad en aplicaciones empresariales."},

  {id:"q290",domain:3,subdomain:"3.4",service:null,difficulty:"hard",
  question:"¿Cómo se evalúa la 'seguridad' de un modelo de generación de imágenes para uso empresarial?",
  options:[{key:"A",text:"Solo se evalúa la resolución y calidad visual de las imágenes generadas."},{key:"B",text:"Evaluación de: generación de contenido NSFW/violento con prompts edge-case, resistencia a deepfakes de personas reales, filtrado de contenido inapropiado, adherencia a políticas de uso, y análisis de similitud con imágenes con copyright del conjunto de entrenamiento."},{key:"C",text:"La seguridad de los modelos de imagen es responsabilidad exclusiva del proveedor."},{key:"D",text:"Solo se necesita verificar que el modelo no genera imágenes de más de cierto tamaño."}],
  answer:"B",
  explanation:"Evaluar seguridad en modelos de imagen incluye: (1) Testing con prompts para contenido NSFW (el modelo debe filtrarlos), (2) Testing de deepfakes con nombres de personas públicas reales, (3) Verificación de filtros para violencia, (4) Similitud con obras protegidas por copyright (búsqueda inversa), (5) Testing de Amazon Titan Image Generator y Stable Diffusion en Bedrock con Guardrails activados."}
];
