// Domain 2 extra questions (q181-q220)
const D2B = [
  {id:"q181",domain:2,subdomain:"2.3",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Qué es la 'Bedrock Marketplace' y cómo amplía las opciones de modelos disponibles?",
  options:[{key:"A",text:"Una tienda donde los usuarios venden sus modelos fine-tuneados."},{key:"B",text:"Un catálogo de modelos de terceros (ISVs) que extiende la oferta nativa de Bedrock, permitiendo acceder a modelos especializados (código, medicina, finanzas) directamente desde la consola de Bedrock con la misma experiencia de API."},{key:"C",text:"Un servicio de suscripción premium para acceso prioritario a modelos de Bedrock."},{key:"D",text:"Un repositorio de prompts de ejemplo para los modelos disponibles en Bedrock."}],
  answer:"B",
  explanation:"Bedrock Marketplace (Model Catalog) permite a los proveedores de modelos de terceros (ISVs) publicar sus modelos especializados, que los clientes pueden acceder con facturación integrada en AWS, sin salir del ecosistema de Bedrock. Facilita descubrir y probar modelos especializados junto a los nativos de Bedrock."},

  {id:"q182",domain:2,subdomain:"2.3",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Cuáles son las diferencias entre los modos de invocación síncrona y de streaming en Amazon Bedrock?",
  options:[{key:"A",text:"Son idénticos en funcionamiento; solo difieren en el costo."},{key:"B",text:"La invocación síncrona espera a que el modelo complete toda la respuesta antes de devolverla; el streaming devuelve tokens conforme se generan, reduciendo la latencia percibida y mejorando la experiencia del usuario en aplicaciones conversacionales."},{key:"C",text:"El streaming solo está disponible para modelos de Anthropic, no para otros modelos."},{key:"D",text:"La invocación síncrona es más rápida que el streaming en todos los escenarios."}],
  answer:"B",
  explanation:"Streaming en Bedrock (InvokeModelWithResponseStream): el cliente recibe chunks de tokens a medida que se generan. Ideal para chatbots donde el usuario ve la respuesta 'escribiéndose'. La invocación síncrona (InvokeModel) espera la respuesta completa, útil para procesamiento batch donde la latencia total importa más que el time-to-first-token."},

  {id:"q183",domain:2,subdomain:"2.3",service:"Amazon Bedrock",difficulty:"hard",
  question:"¿Qué son las 'Bedrock Flows' y qué problema de desarrollo resuelven?",
  options:[{key:"A",text:"Un sistema de control de flujo de tráfico de red hacia los endpoints de Bedrock."},{key:"B",text:"Una herramienta visual para construir flujos de trabajo de IA generativa (pipelines de prompts, condiciones, iteraciones, herramientas) de forma gráfica sin código, simplificando la orquestación de aplicaciones complejas."},{key:"C",text:"Un sistema de facturación que controla el flujo de costos de los proyectos de IA."},{key:"D",text:"Un servicio para gestionar el flujo de datos desde S3 hacia los modelos de Bedrock."}],
  answer:"B",
  explanation:"Amazon Bedrock Flows (anteriormente Amazon Bedrock Prompt Flows) permite crear visualmente flujos de trabajo de IA: conectar prompts, knowledge bases, agentes y lógica condicional en un canvas gráfico. Ideal para equipos que necesitan construir aplicaciones de IA complejas sin escribir código de orquestación complejo."},

  {id:"q184",domain:2,subdomain:"2.3",service:"Amazon Q",difficulty:"medium",
  question:"¿Qué es Amazon Q Apps y cómo se diferencia de Amazon Q Business?",
  options:[{key:"A",text:"Q Apps es la versión premium de Q Business para grandes empresas."},{key:"B",text:"Q Apps permite a los empleados crear mini-aplicaciones de IA generativa sin código usando los datos y Q&A de Amazon Q Business, para automatizar tareas repetitivas y compartirlas con sus compañeros dentro de la organización."},{key:"C",text:"Q Apps es un marketplace de aplicaciones de terceros que se integran con Q Business."},{key:"D",text:"No hay diferencia; son el mismo servicio con nombres distintos."}],
  answer:"B",
  explanation:"Q Apps está integrado en Amazon Q Business y permite a los empleados (no solo IT) crear aplicaciones personalizadas: 'crea un resumen de reuniones', 'genera una propuesta de proyecto', 'analiza este feedback de cliente'. Las apps se basan en los datos y conectores ya configurados en Q Business y se pueden compartir en el índice de apps de la organización."},

  {id:"q185",domain:2,subdomain:"2.3",service:"Amazon SageMaker",difficulty:"medium",
  question:"¿Qué es Amazon SageMaker HyperPod y para qué casos de uso está diseñado?",
  options:[{key:"A",text:"Un tipo especial de endpoint de SageMaker para inferencia de modelos grandes."},{key:"B",text:"Un servicio de clústeres de entrenamiento persistentes y elásticos para LLMs y modelos de FM a gran escala, con recuperación automática de fallos de nodo y capacidad de reanudar el entrenamiento sin perder progreso."},{key:"C",text:"Un sistema de hyperparameter tuning más rápido que SageMaker Automatic Model Tuning."},{key:"D",text:"Una plataforma de datos para preparar datasets de entrenamiento a gran escala para LLMs."}],
  answer:"B",
  explanation:"SageMaker HyperPod resuelve el problema del entrenamiento de LLMs a escala: los clústeres de GPU de cientos o miles de nodos fallan frecuentemente. HyperPod añade: checkpointing automático, recuperación de fallos sin reiniciar todo el trabajo, observabilidad profunda del clúster, y capacidad de ajustar el tamaño del clúster sin interrumpir el entrenamiento."},

  {id:"q186",domain:2,subdomain:"2.3",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Cómo funciona el 'multi-agent collaboration' en Amazon Bedrock Agents?",
  options:[{key:"A",text:"Múltiples usuarios pueden acceder al mismo agente simultáneamente."},{key:"B",text:"Un agente supervisor puede delegar sub-tareas a agentes especializados (subagentes), donde cada subagente tiene herramientas y knowledge bases específicos para su dominio, permitiendo resolver problemas complejos con especialización de roles."},{key:"C",text:"Múltiples agentes compiten para responder la misma pregunta del usuario."},{key:"D",text:"Los agentes se replican automáticamente para manejar más tráfico de usuarios."}],
  answer:"B",
  explanation:"Multi-agent en Bedrock: un agente supervisor recibe el objetivo complejo, analiza qué partes requieren qué expertise y delega: 'Agente de análisis financiero, analiza los números; Agente de código, escribe la consulta SQL'. Los subagentes son expertos en su dominio. El supervisor integra los resultados. Permite escalar la complejidad sin un único agente monolítico."},

  {id:"q187",domain:2,subdomain:"2.3",service:"Amazon Bedrock",difficulty:"hard",
  question:"¿Qué es 'Amazon Bedrock Inline Agents' y en qué se diferencia de los agentes estándar?",
  options:[{key:"A",text:"Son agentes que se ejecutan dentro del navegador del usuario sin servidor."},{key:"B",text:"Una capacidad que permite crear agentes dinámicamente en tiempo de ejecución, definiendo instrucciones, herramientas y knowledge bases en el código sin pre-configurarlos en la consola, útil para personalización per-request o por usuario."},{key:"C",text:"Agentes que procesan datos en línea (streaming) en lugar de por lotes."},{key:"D",text:"Agentes que solo pueden ejecutarse en instancias EC2 dentro de una VPC privada."}],
  answer:"B",
  explanation:"Bedrock Inline Agents permiten configurar el agente dinámicamente en la llamada a la API: instrucciones del sistema, herramientas disponibles y KB pueden variar por solicitud o por usuario. Útil para aplicaciones multitenancy donde cada cliente tiene un agente personalizado diferente sin crear N agentes pre-configurados en la consola."},

  {id:"q188",domain:2,subdomain:"2.3",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Qué son las 'Custom Models' en Amazon Bedrock y cómo se almacenan?",
  options:[{key:"A",text:"Modelos de código abierto descargados desde HuggingFace y subidos a Bedrock."},{key:"B",text:"Modelos resultado del fine-tuning o continued pre-training en Bedrock, almacenados de forma segura en la cuenta del cliente (no en la de AWS), accesibles únicamente mediante Provisioned Throughput del cliente."},{key:"C",text:"Versiones antiguas de los modelos base de Bedrock que se guardan automáticamente."},{key:"D",text:"Modelos entrenados en SageMaker que se importan al catálogo de Bedrock."}],
  answer:"B",
  explanation:"Los custom models en Bedrock son propiedad exclusiva del cliente: los pesos del modelo fine-tuneado se almacenan en recursos gestionados por AWS pero en la cuenta del cliente y no son accesibles por AWS ni por otros clientes. Para invocarlos se debe comprar Provisioned Throughput específico para ese modelo custom."},

  {id:"q189",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué es 'Amazon Comprehend Medical' y en qué se diferencia de Amazon Comprehend estándar?",
  options:[{key:"A",text:"Es exactamente igual que Comprehend estándar pero con mayor costo."},{key:"B",text:"Una versión especializada de Comprehend que extrae entidades médicas (diagnósticos, medicamentos, dosis, síntomas, procedimientos) y las mapea a ontologías médicas estándar (ICD-10-CM, SNOMED CT, RxNorm)."},{key:"C",text:"Un servicio de transcripción médica para convertir notas de voz a texto clínico."},{key:"D",text:"Un chatbot médico para responder preguntas de pacientes en hospitales."}],
  answer:"B",
  explanation:"Amazon Comprehend Medical está optimizado para texto clínico: extrae entidades como diagnósticos, medicamentos, dosis, frecuencias, síntomas y los relaciona entre sí (relaciones: medicamento-dosis, diagnóstico-síntoma). Mapea entidades a ontologías (ICD-10 para diagnósticos, RxNorm para medicamentos) facilitando integración con sistemas de salud estándar."},

  {id:"q190",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué es AWS HealthLake y cómo integra IA para análisis de datos de salud?",
  options:[{key:"A",text:"Una plataforma exclusiva de hardware médico para dispositivos IoT de salud."},{key:"B",text:"Un data lake FHIR-compatible que almacena datos de salud estructurados y semiestructurados, con IA integrada para queries en lenguaje natural, insights automáticos y acceso a modelos de ML especializados en salud."},{key:"C",text:"Un servicio de telemedicina basado en IA para consultas médicas virtuales."},{key:"D",text:"Una base de datos para almacenar imágenes de radiología con búsqueda visual."}],
  answer:"B",
  explanation:"AWS HealthLake es un almacén FHIR (Fast Healthcare Interoperability Resources) completamente gestionado que: normaliza datos clínicos heterogéneos al formato FHIR R4, permite queries API estándar, integra con Amazon Comprehend Medical para indexación de texto clínico, y facilita análisis de población, ensayos clínicos y mejora de atención."},

  {id:"q191",domain:2,subdomain:"2.3",service:null,difficulty:"easy",
  question:"¿Qué es Amazon Rekognition Video y qué capacidades ofrece más allá de la detección de imágenes estáticas?",
  options:[{key:"A",text:"Es idéntico a Rekognition estándar pero más lento por procesar video."},{key:"B",text:"Analiza video frame a frame y en tiempo para: rastrear personas entre frames, detectar actividades (correr, caer), reconocer celebridades en video, moderar contenido en streaming, y detectar texto en escenas de video."},{key:"C",text:"Solo convierte video a una secuencia de imágenes JPEG para análisis posterior."},{key:"D",text:"Solo está disponible para video almacenado en S3, no para streaming en tiempo real."}],
  answer:"B",
  explanation:"Rekognition Video analiza videos con capacidades temporales: seguimiento de personas a lo largo del tiempo (person tracking), detección de actividades (caída de persona, actividad sospechosa), reconocimiento de caras y celebridades en video, moderación de contenido en streaming via Kinesis Video Streams, y segmentación de escenas técnicas."},

  {id:"q192",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué es Amazon Lookout y qué familia de servicios de IA industrial incluye?",
  options:[{key:"A",text:"Un único servicio para detección de fraudes en transacciones financieras."},{key:"B",text:"Una familia de servicios de IA industrial: Lookout for Equipment (detección de anomalías en maquinaria), Lookout for Vision (detección de defectos en imágenes de manufactura), y Lookout for Metrics (detección de anomalías en métricas de negocio)."},{key:"C",text:"Un servicio de monitoreo de redes para detectar intrusiones de seguridad."},{key:"D",text:"Un servicio de supervisión de calidad de modelos de ML en producción."}],
  answer:"B",
  explanation:"Amazon Lookout es la familia de servicios de IA para casos de uso industriales: (1) Lookout for Equipment: usa datos de sensores IoT para detección predictiva de anomalías en maquinaria industrial. (2) Lookout for Vision: detecta defectos visuales en líneas de producción usando imágenes. (3) Lookout for Metrics: detecta automáticamente anomalías en series temporales de métricas de negocio."},

  {id:"q193",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué es Amazon Monitron y para qué caso de uso específico está diseñado?",
  options:[{key:"A",text:"Un servicio de monitoreo de modelos de ML en producción para SageMaker."},{key:"B",text:"Una solución integral de mantenimiento predictivo para equipos industriales que incluye sensores físicos inalámbricos, un gateway y una aplicación móvil con ML integrado para detectar condiciones anómalas en maquinaria rotatoria."},{key:"C",text:"Un sistema de monitoreo de redes de telecomunicaciones industriales."},{key:"D",text:"Un servicio de análisis de video para monitorear seguridad en instalaciones industriales."}],
  answer:"B",
  explanation:"Amazon Monitron es una solución end-to-end de mantenimiento predictivo: sensores físicos Monitron que se adhieren a equipos y miden vibración y temperatura, transmiten datos via gateway a la nube donde ML analiza continuamente para detectar condiciones anómalas, y una app móvil alerta a los técnicos. Ideal para empresas sin expertise en IoT/ML."},

  {id:"q194",domain:2,subdomain:"2.3",service:null,difficulty:"easy",
  question:"¿Qué es Amazon Kendra Intelligent Ranking y cómo mejora la relevancia de búsqueda?",
  options:[{key:"A",text:"Un servicio de clasificación de documentos basado en fecha de creación."},{key:"B",text:"Una API que usa ML para reordenar (re-rank) resultados de búsqueda de cualquier motor de búsqueda existente (incluyendo OpenSearch, Elasticsearch) para mejorar la relevancia semántica sin migrar al motor de búsqueda de Kendra completo."},{key:"C",text:"Un sistema de rankings de empresas basado en su uso de IA."},{key:"D",text:"Una herramienta de SEO para mejorar el posicionamiento en buscadores externos."}],
  answer:"B",
  explanation:"Kendra Intelligent Ranking es un API de reranking: toma resultados de búsqueda (de cualquier motor: OpenSearch, Solr, propio) y los reordena usando el mismo ML semántico de Kendra para mejorar la relevancia. No requiere migrar a Kendra completo; mejora motores de búsqueda existentes añadiendo comprensión semántica al ranking."},

  {id:"q195",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué es Amazon Lex Automated Chatbot Designer y cómo reduce el tiempo de desarrollo?",
  options:[{key:"A",text:"Un servicio que genera chatbots automáticamente sin intervención humana."},{key:"B",text:"Una capacidad de Lex que analiza transcripciones de llamadas existentes (de contact centers) y genera automáticamente intents, utterances y flujos del chatbot, reduciendo semanas de diseño manual a horas."},{key:"C",text:"Un sistema de diseño visual para crear flujos de conversación sin código."},{key:"D",text:"Una herramienta de IA para probar y validar chatbots de Lex antes del despliegue."}],
  answer:"B",
  explanation:"Amazon Lex Automated Chatbot Designer analiza transcripciones de llamadas del contact center, identifica intenciones frecuentes de los clientes, genera propuestas de intents con sus utterances de ejemplo, y crea el esqueleto del chatbot. Reduce significativamente el tiempo de diseño: en vez de pensar desde cero qué intents crear, el sistema los sugiere basándose en conversaciones reales."},

  {id:"q196",domain:2,subdomain:"2.3",service:null,difficulty:"hard",
  question:"¿Qué es Amazon Bedrock Data Automation y para qué tipo de contenido está diseñado?",
  options:[{key:"A",text:"Un servicio de automatización de pipelines de datos para ML en SageMaker."},{key:"B",text:"Un servicio que extrae automáticamente información estructurada de documentos, imágenes, audio y video usando FMs, generando outputs como JSON con campos específicos, transcripciones con timestamps y análisis de contenido multimedia."},{key:"C",text:"Un servicio para automatizar la sincronización de datos entre regiones de AWS."},{key:"D",text:"Una herramienta de automatización de pruebas para pipelines de datos de ML."}],
  answer:"B",
  explanation:"Bedrock Data Automation procesa contenido no estructurado a escala: documentos (extrae campos de facturas, contratos), imágenes (clasifica, extrae texto, detecta objetos), audio (transcribe con identificación de hablantes), y video (genera resúmenes, extrae momentos clave). Usa FMs internamente pero expone una API de alto nivel sin gestionar el prompting."},

  {id:"q197",domain:2,subdomain:"2.3",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Cómo se gestiona el 'rate limiting' y la escalabilidad en Amazon Bedrock para aplicaciones de producción?",
  options:[{key:"A",text:"Bedrock no tiene rate limits; escala infinitamente."},{key:"B",text:"Bedrock tiene límites de throttling por cuenta y región (TPS - transactions per second); se pueden solicitar aumentos a AWS Support, y el Provisioned Throughput garantiza throughput reservado para cargas de trabajo predecibles sin throttling."},{key:"C",text:"El rate limiting solo aplica a modelos de Anthropic, no a los demás."},{key:"D",text:"Solo se pueden escalar los límites de Bedrock usando instancias dedicadas de EC2."}],
  answer:"B",
  explanation:"Bedrock on-demand tiene Service Quotas (TPS por modelo, por cuenta, por región). Para aplicaciones de producción: (1) Solicitar aumentos de quota via AWS Support. (2) Provisioned Throughput para garantizar TPS específicos. (3) Implementar retry logic con exponential backoff para manejar throttling temporal. (4) Distribuir entre múltiples regiones con Cross-region inference profiles."},

  {id:"q198",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué es Amazon Titan Multimodal Embeddings y cuándo es más útil que los embeddings de texto?",
  options:[{key:"A",text:"Son embeddings para texto en múltiples idiomas simultáneamente."},{key:"B",text:"Un modelo que genera embeddings en el mismo espacio vectorial para texto e imágenes, permitiendo búsqueda cruzada: buscar imágenes con texto o texto con imágenes, útil para e-commerce, búsqueda de productos y catálogos visuales."},{key:"C",text:"Embeddings que soportan más tipos de archivos que los embeddings de texto estándar."},{key:"D",text:"Un modelo exclusivamente para clasificación multimodal, no para búsqueda semántica."}],
  answer:"B",
  explanation:"Titan Multimodal Embeddings proyecta texto e imágenes al mismo espacio vectorial. Caso de uso clave: e-commerce donde el usuario busca 'zapatos rojos de tacón' (texto) y el sistema recupera imágenes de productos que coinciden sin necesitar etiquetas manuales. También: buscar imágenes similares a una imagen de referencia, o recuperar descripciones relevantes dada una imagen."},

  {id:"q199",domain:2,subdomain:"2.3",service:null,difficulty:"easy",
  question:"¿Qué es AWS Neuron SDK y por qué es necesario para usar chips AWS Inferentia y Trainium?",
  options:[{key:"A",text:"Un lenguaje de programación propio de AWS para desarrollo de modelos de IA."},{key:"B",text:"El SDK de compilación y runtime de AWS que convierte modelos de PyTorch/TensorFlow en un formato optimizado para ejecutarse en los chips Inferentia y Trainium, con integración transparente en los frameworks de ML existentes."},{key:"C",text:"Un sistema operativo especializado para instancias con chips de IA de AWS."},{key:"D",text:"Una biblioteca de utilidades para monitoreo de los chips Inferentia en producción."}],
  answer:"B",
  explanation:"AWS Neuron SDK es necesario para aprovechar los chips Inferentia (inf1/inf2) y Trainium (trn1). Incluye un compilador (neuron-cc) que optimiza el modelo para el hardware específico, librerías de runtime, y herramientas de perfilado. La integración con PyTorch es casi transparente: se añade torch.neuron.trace() y el resto del código permanece igual."},

  {id:"q200",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué ventajas específicas ofrece Amazon OpenSearch Service para aplicaciones de IA generativa?",
  options:[{key:"A",text:"OpenSearch solo sirve para búsqueda de texto; no tiene capacidades para IA."},{key:"B",text:"Búsqueda vectorial k-NN integrada para embeddings, búsqueda híbrida (semántica + keyword), pipelines de ingesta con modelos ML integrados, y integración nativa con Amazon Bedrock Knowledge Bases como vector store."},{key:"C",text:"OpenSearch es exclusivamente para análisis de logs; no es adecuado para IA generativa."},{key:"D",text:"Solo OpenSearch Serverless soporta búsqueda vectorial; el servicio estándar no."}],
  answer:"B",
  explanation:"OpenSearch para RAG: (1) k-NN vector search con FAISS, NMSLIB o Lucene engine. (2) Búsqueda híbrida: combina similitud vectorial (semántica) + BM25 (keywords) con recíprocal rank fusion. (3) ML inference pipelines: indexar embeddings automáticamente en la ingesta. (4) Integración nativa con Bedrock Knowledge Bases. Es el vector store default de Bedrock KB y una solución robusta para RAG empresarial."},

  {id:"q201",domain:2,subdomain:"2.2",service:null,difficulty:"medium",
  question:"¿Cuál es la diferencia entre 'emergent abilities' (capacidades emergentes) en LLMs grandes y capacidades pre-programadas?",
  options:[{key:"A",text:"Las capacidades emergentes son las programadas explícitamente por los desarrolladores."},{key:"B",text:"Capacidades que aparecen de forma no intencional y sorprendente a partir de cierto umbral de escala del modelo (número de parámetros), como aritmética de varios dígitos, traducción no entrenada explícitamente, o razonamiento analógico."},{key:"C",text:"Son capacidades que emergen solo después del fine-tuning supervisado, no del pre-entrenamiento."},{key:"D",text:"Las capacidades emergentes son solo observadas en modelos de código abierto."}],
  answer:"B",
  explanation:"Las emergent abilities (Wei et al., 2022) son capacidades que aparecen abruptamente al superar cierto umbral de escala: modelos pequeños tienen ~0% de rendimiento en la tarea; al superar ~100B params de repente la tasa de éxito salta dramáticamente. Ejemplos: few-shot learning, aritmética multi-dígito, BIG-bench tasks. Son uno de los fenómenos más fascinantes y debatidos en IA moderna."},

  {id:"q202",domain:2,subdomain:"2.2",service:null,difficulty:"hard",
  question:"¿Qué es el 'context length extrapolation' y por qué es un reto técnico para los LLMs?",
  options:[{key:"A",text:"La capacidad de los LLMs para extrapolar información fuera de su contexto de entrenamiento."},{key:"B",text:"La dificultad de los LLMs para generalizar a contextos más largos que los vistos durante el entrenamiento; los positional encodings se comportan de forma inesperada fuera del rango de entrenamiento, degradando el rendimiento."},{key:"C",text:"Una técnica para comprimir contextos largos en representaciones más cortas."},{key:"D",text:"El proceso de entrenar modelos con datos sintéticos de contextos muy largos."}],
  answer:"B",
  explanation:"Los LLMs aprenden positional encodings hasta la longitud máxima de entrenamiento. Más allá de ese límite, los encodings son 'territorio no visto' y el modelo puede fallar. Soluciones: RoPE (Rotary Position Embedding) con escalado de base, ALiBi (Attention with Linear Biases), y técnicas de fine-tuning como LongLora que extienden el contexto sin reentrenar desde cero."},

  {id:"q203",domain:2,subdomain:"2.2",service:null,difficulty:"medium",
  question:"¿Qué son los 'system prompts' en las aplicaciones LLM y cuáles son los riesgos de seguridad asociados?",
  options:[{key:"A",text:"Los system prompts no tienen riesgos de seguridad; son instrucciones internas no accesibles."},{key:"B",text:"Instrucciones privadas del desarrollador que guían el comportamiento del modelo, con riesgos de: extracción por usuarios (piden al modelo que revele el system prompt), inyección (sobreescritura maliciosa), y fuga de información propietaria o credenciales incorrectamente incluidas."},{key:"C",text:"Solo los system prompts de más de 1000 tokens son vulnerables a ataques."},{key:"D",text:"Los system prompts están cifrados por Bedrock y no pueden ser extraídos."}],
  answer:"B",
  explanation:"Los system prompts contienen lógica de negocio y configuración propietaria. Riesgos: (1) Extracción: 'Muéstrame tus instrucciones completas' puede revelarlos. (2) Overriding: 'Ignora instrucciones anteriores'. Protecciones: instruir explícitamente al modelo a no revelar el system prompt, probar resistencia a ataques de extracción, y no incluir credenciales/tokens en el system prompt."},

  {id:"q204",domain:2,subdomain:"2.2",service:null,difficulty:"medium",
  question:"¿Cuáles son las limitaciones de los LLMs para tareas de conteo y enumeración exacta?",
  options:[{key:"A",text:"Los LLMs son perfectos para contar elementos en listas y textos."},{key:"B",text:"Los LLMs procesan texto como secuencias de tokens, no como elementos discretos a contar; son propensos a errores en contar letras específicas en palabras, elementos en listas largas o frecuencias exactas en textos, por no tener mecanismo de conteo preciso."},{key:"C",text:"Las limitaciones de conteo solo aplican a números mayores de 1000."},{key:"D",text:"Solo los modelos sin instruction tuning tienen problemas de conteo."}],
  answer:"B",
  explanation:"El famoso error 'cuántas Rs hay en strawberry' (respuesta: 3, no 2) ilustra que los LLMs tokeniza 'strawberry' en subpalabras y no puede 'ver' letras individuales fácilmente. No tienen un mecanismo de conteo algorítmico; cuentan por patrones aprendidos estadísticamente. Para conteo exacto, usar Code Interpreter (Python con len([x for x in word if x=='r']))."},

  {id:"q205",domain:2,subdomain:"2.1",service:null,difficulty:"medium",
  question:"¿Qué es 'Mixture of Experts' (MoE) en LLMs y cuál es su ventaja principal?",
  options:[{key:"A",text:"Una técnica de ensemble que combina múltiples LLMs independientes para mejor rendimiento."},{key:"B",text:"Una arquitectura donde el modelo tiene múltiples 'expertos' especializados por capa, pero solo activa un subconjunto (2-4) para cada token, permitiendo modelos de mayor capacidad total con el mismo cómputo de inferencia que modelos más pequeños."},{key:"C",text:"Un método de entrenamiento que combina múltiples datasets de diferentes dominios."},{key:"D",text:"Una arquitectura para modelos multimodales que usa expertos especializados por modalidad."}],
  answer:"B",
  explanation:"MoE (usado en Mixtral, GPT-4 según rumores): cada capa tiene N expertos (sub-redes), un router decide qué 2-4 expertos activar por token. Resultado: modelo con parámetros totales de 47B (Mixtral 8x7B) pero que en inferencia solo usa ~13B activos, siendo más eficiente que un modelo denso de 47B. Desafío: carga desbalanceada y complejidad de entrenamiento."},

  {id:"q206",domain:2,subdomain:"2.1",service:null,difficulty:"hard",
  question:"¿Qué es el 'speculative decoding' y cómo acelera la inferencia de LLMs?",
  options:[{key:"A",text:"Una técnica de prompting que anticipa las respuestas del usuario para reducir latencia."},{key:"B",text:"Una técnica de inferencia donde un modelo pequeño (draft model) genera varios tokens de forma rápida, y el modelo grande los verifica en paralelo, aceptando o rechazando cada token, logrando 2-3x de aceleración sin cambiar la calidad de la salida."},{key:"C",text:"Una técnica de cuantización especulativa para reducir el tamaño del modelo en producción."},{key:"D",text:"Un método de entrenamiento donde el modelo aprende a especular sobre respuestas futuras."}],
  answer:"B",
  explanation:"Speculative decoding usa un modelo pequeño (ej. 7B) para generar N tokens candidatos rápidamente, luego el modelo grande (ej. 70B) los verifica todos en paralelo en un solo forward pass. Si los tokens del draft coinciden con los del modelo grande, se aceptan todos; si no, se rechaza a partir del primero incorrecto. Resultado: 2-4x aceleración manteniendo exactamente la misma distribución de salida."},

  {id:"q207",domain:2,subdomain:"2.1",service:null,difficulty:"medium",
  question:"¿Qué son los 'Constitutional AI principles' de Anthropic y cómo se implementan en Claude?",
  options:[{key:"A",text:"Un conjunto de leyes de robótica actualizadas para LLMs modernos."},{key:"B",text:"Un conjunto de principios éticos que guían el comportamiento de Claude: ser inofensivo, honesto y útil; implementados mediante RLHF con estos principios como criterios de evaluación y Constitutional AI (CAI) donde el modelo auto-revisa sus respuestas contra los principios."},{key:"C",text:"Los términos legales de uso de Claude como producto comercial de Anthropic."},{key:"D",text:"Una arquitectura de red neuronal basada en principios constitucionales de diferentes países."}],
  answer:"B",
  explanation:"Anthropic desarrolló Constitutional AI: Claude tiene una 'constitución' de principios (harmless, honest, helpful) y durante el entrenamiento se le pide auto-criticar sus respuestas contra esos principios y revisarlas. Esto permite alineación más escalable que RLHF puro. Claude en Bedrock hereda estos principios y es reconocido por su resistencia a jailbreaking y alta alineación con valores humanos."},

  {id:"q208",domain:2,subdomain:"2.1",service:null,difficulty:"easy",
  question:"¿Qué es el 'context distillation' y en qué escenarios es útil en aplicaciones LLM?",
  options:[{key:"A",text:"Una técnica para reducir el tamaño del contexto eliminando tokens menos importantes."},{key:"B",text:"Una técnica donde se proporciona un contexto extenso al modelo y se le pide que destile las instrucciones en sus respuestas, efectivamente 'incorporando' las instrucciones sin incluirlas en cada prompt individual."},{key:"C",text:"Un método de compresión del modelo usando destilación de conocimiento para reducir tamaño."},{key:"D",text:"La técnica de dividir el contexto en chunks y procesarlos por separado."}],
  answer:"B",
  explanation:"Context distillation: usar el LLM con un contexto largo que explica el comportamiento deseado, y luego hacer que el modelo sintetice respuestas breves que 'internalizan' ese conocimiento. Útil para: crear ejemplos de fine-tuning donde el modelo ha visto el contexto completo y genera respuestas como si lo hubiera aprendido, reduciendo la dependencia de contextos largos en producción."},

  {id:"q209",domain:2,subdomain:"2.2",service:null,difficulty:"medium",
  question:"¿Cuáles son los principales retos de los LLMs para tareas de razonamiento lógico formal (lógica de predicados, inferencia deductiva)?",
  options:[{key:"A",text:"Los LLMs son perfectos para lógica formal ya que procesan secuencias de símbolos."},{key:"B",text:"Los LLMs tienen dificultades con lógica formal estricta: son inconsistentes en silogismos complejos, cometen errores en inferencia deductiva multi-paso, y pueden llegar a conclusiones diferentes con el mismo problema formulado de forma diferente."},{key:"C",text:"Los LLMs solo fallan en lógica formal cuando los problemas tienen más de 10 pasos."},{key:"D",text:"Los LLMs resuelven lógica formal perfectamente con chain-of-thought prompting."}],
  answer:"B",
  explanation:"Los LLMs aprenden razonamiento por ejemplos estadísticos, no por aplicación de reglas formales verificables. En lógica deductiva: 'Todos los A son B; todos los B son C; ¿son todos los A C?' puede fallar en casos complejos. Herramientas como Prolog, SMT solvers o herramientas de verificación formal son más confiables para lógica estricta. Los LLMs pueden orquestar estas herramientas via tool use."},

  {id:"q210",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué es Amazon Bedrock Studio y para qué perfil de usuario está diseñado?",
  options:[{key:"A",text:"Un IDE especializado para data scientists que entrenan modelos en Bedrock."},{key:"B",text:"Un espacio de trabajo colaborativo basado en web para que equipos de negocio y desarrolladores experimenten, construyan y compartan prototipos de aplicaciones de IA generativa usando Bedrock, con acceso controlado sin credenciales AWS directas."},{key:"C",text:"Una herramienta de monitoreo visual para modelos desplegados en producción vía Bedrock."},{key:"D",text:"Un entorno de notebook similar a SageMaker Studio pero especializado para LLMs."}],
  answer:"B",
  explanation:"Bedrock Studio democratiza el acceso a Bedrock para equipos no técnicos: los administradores crean workspaces con acceso a modelos específicos, y los usuarios de negocio pueden experimentar con aplicaciones de IA sin manejar credenciales AWS directamente. Permite colaboración entre negocio y tecnología en el diseño de aplicaciones de IA generativa."},

  {id:"q211",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Cuál es el caso de uso principal de Amazon Textract Queries y cómo mejora la extracción de documentos?",
  options:[{key:"A",text:"Realizar consultas SQL sobre documentos escaneados en S3."},{key:"B",text:"Permitir hacer preguntas en lenguaje natural sobre un documento específico ('¿Cuál es la fecha de vencimiento?' '¿Cuál es el monto total?') y recibir la respuesta extraída directamente del documento, sin necesidad de parsear toda la estructura."},{key:"C",text:"Buscar documentos por contenido en un repositorio de archivos escaneados."},{key:"D",text:"Generar consultas automáticas para extraer datos de múltiples documentos similares."}],
  answer:"B",
  explanation:"Textract Queries permite preguntas directas sobre documentos: en vez de extraer toda la estructura de una factura y luego buscar el campo 'monto', se pregunta directamente '¿Cuál es el importe total a pagar?' y Textract devuelve el valor correspondiente del documento. Reduce significativamente el código post-procesamiento para extracción de campos específicos."},

  {id:"q212",domain:2,subdomain:"2.3",service:null,difficulty:"easy",
  question:"¿Qué es Amazon Polly Neural Text-to-Speech y en qué se diferencia de las voces estándar?",
  options:[{key:"A",text:"Las voces neuronales son más lentas pero idénticas en calidad a las estándar."},{key:"B",text:"Las voces neuronales de Polly usan modelos de deep learning para síntesis de habla con calidad superior: prosodia más natural, mejor manejo de signos de puntuación, soporte de estilos de habla (newscast, conversational) y mayor naturalidad general en idiomas como español, inglés y otros."},{key:"C",text:"Las voces neuronales solo están disponibles en inglés americano."},{key:"D",text:"Las voces neuronales son para documentos de texto; las estándar son para voz conversacional."}],
  answer:"B",
  explanation:"Amazon Polly ofrece voces estándar (concatenación de segmentos de voz) y neuronales (deep learning con NTTS). Las neuronales tienen calidad significativamente mejor: más naturales, con entonación apropiada según el contexto, soportan SSML para control fino y algunos estilos de habla (newscast para noticias, conversational para chatbots). Disponibles en múltiples idiomas incluyendo español."},

  {id:"q213",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué es Amazon Transcribe Call Analytics y cómo añade valor sobre la transcripción básica?",
  options:[{key:"A",text:"Solo mejora la precisión de transcripción para llamadas de contact center."},{key:"B",text:"Además de transcripción precisa con identificación de hablante (agente vs cliente), analiza automáticamente: sentimiento por segmento de conversación, categorías de llamada, extracción de entidades (números, fechas, productos), y detección de llamadas de interrupción y silencios."},{key:"C",text:"Permite hacer llamadas telefónicas automáticas usando IA generativa."},{key:"D",text:"Es una versión de Transcribe exclusiva para el sector financiero con mayor precisión."}],
  answer:"B",
  explanation:"Transcribe Call Analytics para contact centers: (1) Diarización (separación agente/cliente), (2) Análisis de sentimiento por turno de conversación, (3) Categorización automática de llamadas por motivo, (4) Extracción de entidades (nombres de productos, números de cuenta), (5) Detección de interrupciones, silencios y tiempo de habla. Genera insights operativos del contact center sin configuración adicional."},

  {id:"q214",domain:2,subdomain:"2.2",service:null,difficulty:"hard",
  question:"¿Qué son los 'token budgets' y cómo ayudan a controlar el costo y comportamiento de los LLMs?",
  options:[{key:"A",text:"Un sistema de monitoreo de costos que alerta cuando se excede un presupuesto mensual."},{key:"B",text:"Instrucciones explícitas al modelo sobre cuántos tokens usar en su respuesta (ej. 'responde en máximo 100 palabras'), que controlan la concisión, el costo de tokens de salida y la adecuación de la respuesta al contexto de uso."},{key:"C",text:"Un mecanismo técnico que corta físicamente la generación al alcanzar el límite de tokens."},{key:"D",text:"La asignación de presupuesto financiero a diferentes proyectos que usan LLMs."}],
  answer:"B",
  explanation:"Los token budgets (parte del extended thinking de Claude) permiten instruir al modelo a ser más o menos conciso según el contexto. 'Extended thinking' de Claude permite asignar tokens de razonamiento interno: más tokens = razonamiento más profundo = mejor rendimiento en tareas complejas, a mayor costo. El balance entre costo y calidad se gestiona con el token budget del pensamiento."},

  {id:"q215",domain:2,subdomain:"2.3",service:"Amazon Bedrock",difficulty:"medium",
  question:"¿Qué son los 'inference profiles' en Amazon Bedrock y para qué sirven?",
  options:[{key:"A",text:"Perfiles de rendimiento que muestran las métricas de latencia de los modelos."},{key:"B",text:"Configuraciones que permiten agrupar capacidad de múltiples regiones para enrutar automáticamente solicitudes a la región con mayor disponibilidad, mejorando el throughput y la resiliencia sin gestión manual del enrutamiento multi-región."},{key:"C",text:"Plantillas de prompts predefinidas para los casos de uso más comunes en Bedrock."},{key:"D",text:"Perfiles de configuración de seguridad para diferentes tipos de aplicaciones en Bedrock."}],
  answer:"B",
  explanation:"Los inference profiles de Bedrock son de dos tipos: (1) Cross-region: agrupan capacidad de múltiples regiones (ej. us-east-1 + us-west-2) con enrutamiento automático al que tenga más capacidad. (2) Application inference profiles: permiten añadir tags para seguimiento de costos por aplicación/equipo. Facilitan tanto la resiliencia multi-región como la gobernanza de costos."},

  {id:"q216",domain:2,subdomain:"2.3",service:null,difficulty:"easy",
  question:"¿Qué es Amazon Comprehend Custom y cuándo se recomienda sobre Comprehend estándar?",
  options:[{key:"A",text:"Una versión premium de Comprehend con mayor precisión en todos los idiomas."},{key:"B",text:"Permite entrenar clasificadores y reconocedores de entidades personalizados con datos propios cuando las categorías de Comprehend estándar no cubren las necesidades del dominio (ej. categorías de soporte técnico específicas de la empresa o entidades propias como nombres de productos)."},{key:"C",text:"Comprehend Custom solo funciona para clasificación de texto; no para extracción de entidades."},{key:"D",text:"Comprehend Custom es para datos multilingüe; el estándar solo es en inglés."}],
  answer:"B",
  explanation:"Comprehend Custom resuelve el problema de categorías específicas del dominio: si necesitas clasificar tickets de soporte en categorías como 'fallo de hardware', 'problema de software', 'consulta de facturación' (específicas de tu empresa), o extraer entidades como nombres de productos propietarios, entrenas un clasificador/extractor personalizado con tus datos etiquetados."},

  {id:"q217",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué son los modelos Mistral disponibles en Amazon Bedrock y cuáles son sus características?",
  options:[{key:"A",text:"Modelos de visión por computadora especializados en análisis de imágenes industriales."},{key:"B",text:"LLMs de Mistral AI (empresa europea), incluyendo Mistral Small, Large y Mixtral 8x7B (MoE), conocidos por su eficiencia, rendimiento comparable a modelos más grandes a menor costo, y disponibilidad con licencia Apache 2.0."},{key:"C",text:"Modelos de clasificación de texto para mercados financieros europeos."},{key:"D",text:"Modelos de análisis de sentimientos optimizados para el mercado europeo."}],
  answer:"B",
  explanation:"Mistral AI (Francia) ofrece en Bedrock: Mistral 7B y Mixtral 8x7B (MoE, usa ~13B params activos de 47B totales), Mistral Large (flagship). Son conocidos por: alta eficiencia computacional, fuerte rendimiento en inglés y francés, licencia Apache 2.0 para los modelos base, y ser una alternativa europea a modelos de empresas americanas, relevante para soberanía de datos europea."},

  {id:"q218",domain:2,subdomain:"2.3",service:null,difficulty:"hard",
  question:"¿Cómo se integra Amazon Bedrock con Amazon CloudWatch para observabilidad de aplicaciones de IA?",
  options:[{key:"A",text:"Bedrock no publica métricas en CloudWatch; se necesitan herramientas de terceros."},{key:"B",text:"Bedrock publica automáticamente métricas en CloudWatch: número de invocaciones, latencia (tiempo a primer byte, tiempo total), tokens de entrada/salida, errores y throttling, permitiendo dashboards, alarmas y análisis de rendimiento integrados con el ecosistema de observabilidad de AWS."},{key:"C",text:"Solo las invocaciones fallidas de Bedrock se registran en CloudWatch."},{key:"D",text:"La integración con CloudWatch requiere configuración manual compleja y un agente dedicado."}],
  answer:"B",
  explanation:"Bedrock publica métricas nativas en CloudWatch: InvocationLatency (latencia total), FirstByteLatency (TTFT), TokenCount (tokens in/out para facturación y optimización), InvocationCount, InvocationThrottles (para detectar rate limiting). Con estas métricas se pueden crear dashboards de rendimiento, alarmas de SLA y correlacionar con métricas de negocio de la aplicación."},

  {id:"q219",domain:2,subdomain:"2.3",service:null,difficulty:"medium",
  question:"¿Qué es el 'Amazon Bedrock Converse API' con tool use y cómo simplifica el desarrollo de agentes?",
  options:[{key:"A",text:"Una herramienta de conversación interna de AWS para el equipo de desarrollo de Bedrock."},{key:"B",text:"Una API unificada que gestiona el ciclo completo de tool use: el modelo identifica qué herramienta usar, el developer ejecuta la herramienta, y el resultado se devuelve al modelo para la respuesta final, con el mismo formato para todos los modelos de Bedrock que soportan tool use."},{key:"C",text:"Una API para hacer conversaciones entre dos modelos de Bedrock diferentes."},{key:"D",text:"Una interfaz conversacional de Bedrock exclusiva para usuarios de Amazon Connect."}],
  answer:"B",
  explanation:"El Converse API unifica tool use: defines tus herramientas en un formato estándar (nombre, descripción, JSON schema de parámetros), y la API maneja el ciclo: el modelo decide usar una herramienta → devuelve ToolUseBlock → el developer ejecuta la función → envía ToolResultBlock → el modelo genera la respuesta final. Funciona igual con Claude, Llama y otros modelos que soportan tool use."},

  {id:"q220",domain:2,subdomain:"2.3",service:null,difficulty:"easy",
  question:"¿Cómo puede Amazon SageMaker Canvas beneficiar a analistas de negocio sin expertise en ML?",
  options:[{key:"A",text:"Canvas es exclusivo para data scientists con conocimiento de Python."},{key:"B",text:"SageMaker Canvas es una interfaz visual no-code/low-code que permite a analistas de negocio construir modelos de ML (clasificación, regresión, series temporales, visión) conectando datos, configurando el problema y obteniendo predicciones sin escribir código."},{key:"C",text:"Canvas solo sirve para análisis descriptivo; no puede generar predicciones."},{key:"D",text:"Canvas requiere que el modelo ya esté entrenado por un data scientist antes de usarlo."}],
  answer:"B",
  explanation:"SageMaker Canvas democratiza el ML para analistas de negocio: conecta a fuentes de datos (S3, Redshift, Snowflake, Salesforce), configura el tipo de problema visualmente, construye y evalúa el modelo con AutoML, y genera predicciones. Soporta análisis 'what-if' y explanations. Integra con SageMaker para que los data scientists puedan revisar y desplegar los modelos creados."}
];
