// Domain 4: Guidelines for Responsible AI (70 questions)
const D4 = [
  {id:"q361",domain:4,subdomain:"4.1",service:null,difficulty:"easy",
  question:"¿Qué es la 'IA responsable' y cuáles son sus principios fundamentales?",
  options:[{key:"A",text:"La IA responsable se refiere únicamente al uso eficiente de recursos computacionales."},{key:"B",text:"Un conjunto de prácticas y principios para desarrollar y desplegar IA de forma ética: equidad (fairness), explicabilidad, privacidad, robustez, seguridad, transparencia e inclusividad."},{key:"C",text:"La certificación legal que AWS emite a los modelos aprobados para uso empresarial."},{key:"D",text:"Un framework técnico para optimizar el rendimiento de los modelos de IA."}],
  answer:"B",
  explanation:"La IA responsable garantiza que los sistemas de IA sean: equitativos (no discriminen), explicables (decisiones comprensibles), privados (protegen datos personales), robustos (funcionan de forma fiable), seguros (no causan daño), transparentes (claros sobre sus capacidades/limitaciones) e inclusivos (accesibles para todos)."},

  {id:"q362",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué es el 'sesgo algorítmico' (algorithmic bias) y cómo puede causar daño?",
  options:[{key:"A",text:"Un parámetro matemático que optimiza el rendimiento del modelo."},{key:"B",text:"Patrones discriminatorios en las predicciones del modelo derivados de datos de entrenamiento sesgados o diseños de modelo inadecuados, que pueden resultar en discriminación por raza, género, edad u otras características protegidas."},{key:"C",text:"El margen de error natural aceptable en cualquier modelo de ML."},{key:"D",text:"Una técnica de optimización que acelera el entrenamiento del modelo."}],
  answer:"B",
  explanation:"El sesgo algorítmico puede manifestarse en: rechazos discriminatorios de crédito, sesgo en contratación (algoritmos que favorecen a un género), diagnósticos médicos menos precisos para minorías, o reconocimiento facial menos preciso para personas de color. Proviene de datos históricos que reflejan desigualdades sociales o de diseños de modelo que amplifican esas desigualdades."},

  {id:"q363",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Cuáles son las principales fuentes de sesgo en los modelos de Machine Learning?",
  options:[{key:"A",text:"El sesgo solo proviene del hardware donde se entrena el modelo."},{key:"B",text:"Sesgo en los datos de entrenamiento (historical bias, representation bias, measurement bias), sesgo de selección, sesgo de etiquetado, y sesgo de diseño del modelo o de las métricas de evaluación."},{key:"C",text:"El sesgo solo existe en modelos de reconocimiento facial, no en otros tipos de IA."},{key:"D",text:"El sesgo se elimina automáticamente con más datos de entrenamiento."}],
  answer:"B",
  explanation:"Fuentes de sesgo: (1) Historical bias: datos que reflejan discriminación histórica (ej. empleados históricos mayoritariamente hombres). (2) Representation bias: subrepresentación de grupos (ej. pocas imágenes de ciertas etnias). (3) Measurement bias: instrumentos de medición menos precisos para ciertos grupos. (4) Label bias: anotadores con prejuicios implícitos."},

  {id:"q364",domain:4,subdomain:"4.1",service:"Amazon SageMaker",difficulty:"medium",
  question:"¿Qué herramientas de AWS ayudan a detectar y mitigar el sesgo en modelos de ML?",
  options:[{key:"A",text:"AWS no ofrece herramientas específicas para detección de sesgo."},{key:"B",text:"Amazon SageMaker Clarify detecta sesgo en datos y modelos, genera informes de equidad con métricas como disparate impact y demographic parity, y proporciona valores SHAP para explicabilidad."},{key:"C",text:"El sesgo solo se puede detectar manualmente mediante auditoría humana."},{key:"D",text:"Solo Amazon Comprehend puede detectar sesgo en datos de texto."}],
  answer:"B",
  explanation:"SageMaker Clarify evalúa: (1) Pre-training bias: ¿los datos de entrenamiento tienen distribuciones desiguales por grupos? (2) Post-training bias: ¿las predicciones son igualmente precisas para todos los grupos? Métricas: Disparate Impact, Class Imbalance, Demographic Parity, Equal Opportunity. Los informes ayudan a identificar y corregir sesgos antes del despliegue."},

  {id:"q365",domain:4,subdomain:"4.1",service:null,difficulty:"hard",
  question:"¿Qué es el 'Disparate Impact' como métrica de equidad y cómo se interpreta?",
  options:[{key:"A",text:"Una métrica que mide la velocidad diferencial de respuesta para distintos grupos de usuarios."},{key:"B",text:"La razón entre la tasa de resultados favorables para el grupo desfavorecido versus el grupo favorecido; según la regla del 80% (four-fifths rule), un ratio < 0.8 indica discriminación potencial."},{key:"C",text:"La diferencia absoluta en accuracy entre el grupo mayoritario y minoritario."},{key:"D",text:"Una métrica de rendimiento que mide el impacto del sesgo en la velocidad del modelo."}],
  answer:"B",
  explanation:"Disparate Impact = P(favorable | grupo_desfavorecido) / P(favorable | grupo_favorecido). Si un modelo de contratación aprueba al 80% de hombres pero solo al 50% de mujeres: DI = 50/80 = 0.625 < 0.8, indicando posible discriminación. La 'four-fifths rule' del EEOC (EE.UU.) establece 0.8 como umbral legal."},

  {id:"q366",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué son las 'características protegidas' en el contexto de la equidad en IA?",
  options:[{key:"A",text:"Variables del modelo que no deben modificarse durante el fine-tuning."},{key:"B",text:"Atributos como raza, género, edad, religión, orientación sexual y discapacidad que están protegidos por ley de discriminación y que los modelos de IA no deben usar de forma directa o indirecta para discriminar."},{key:"C",text:"Datos de entrenamiento con acceso restringido que solo pueden ver los administradores."},{key:"D",text:"Características del modelo que están encriptadas para proteger la propiedad intelectual."}],
  answer:"B",
  explanation:"Las características protegidas (género, raza, edad, religión, discapacidad, etc.) están protegidas por ley (EEOC en EE.UU., GDPR en Europa). Los modelos de IA no deben discriminar basándose en ellas, incluso indirectamente (proxy discrimination: usar código postal puede ser proxy de raza en áreas segregadas). SageMaker Clarify analiza fairness con respecto a estas características."},

  {id:"q367",domain:4,subdomain:"4.1",service:null,difficulty:"hard",
  question:"¿Cuál es la diferencia entre 'equidad de grupo' y 'equidad individual' en los sistemas de IA?",
  options:[{key:"A",text:"Son el mismo concepto; solo difieren en la escala de análisis."},{key:"B",text:"La equidad de grupo requiere que las métricas de rendimiento (accuracy, tasa de aprobación) sean iguales entre grupos demográficos; la equidad individual requiere que personas similares reciban predicciones similares independientemente de su grupo."},{key:"C",text:"La equidad de grupo aplica a modelos de clasificación; la individual a modelos de regresión."},{key:"D",text:"La equidad individual es más fácil de lograr que la equidad de grupo."}],
  answer:"B",
  explanation:"Group fairness: métricas iguales entre grupos (same TPR, FPR para hombres y mujeres). Individual fairness: personas parecidas en características relevantes deben recibir predicciones parecidas. Paradoja de Chouldechova: es matemáticamente imposible satisfacer simultáneamente múltiples definiciones de equidad de grupo. La elección del criterio depende del contexto ético y legal."},

  {id:"q368",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué es el 'Human-in-the-loop' (HITL) y cuándo es esencial en sistemas de IA?",
  options:[{key:"A",text:"Un sistema donde los humanos escriben el código de los modelos de IA."},{key:"B",text:"La incorporación de revisión y aprobación humana en el flujo de decisiones de la IA, especialmente cuando las consecuencias del error son altas (decisiones médicas, legales, financieras importantes o que afectan derechos de las personas)."},{key:"C",text:"Un bucle de entrenamiento continuo donde humanos etiquetan datos en tiempo real."},{key:"D",text:"Un sistema de monitoreo donde humanos supervisan el rendimiento del modelo 24/7."}],
  answer:"B",
  explanation:"HITL es esencial cuando el costo del error es alto: decisiones de crédito, diagnósticos médicos, sentencias judiciales, contratación, beneficios sociales. La IA apoya al humano (segundo par de ojos) pero el humano mantiene responsabilidad de la decisión. Ejemplos: radiologías (IA detecta anomalías, médico confirma), moderación de contenido (IA filtra, humano revisa borderline cases)."},

  {id:"q369",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué implica el principio de 'uso mínimo de datos' (data minimization) en el desarrollo de IA responsable?",
  options:[{key:"A",text:"Usar el menor número posible de datos de entrenamiento para reducir costos."},{key:"B",text:"Recopilar y usar solo los datos estrictamente necesarios para el propósito del sistema de IA, evitando acumular datos personales más allá de lo requerido, alineado con GDPR y principios de privacidad."},{key:"C",text:"Minimizar el tamaño del dataset para reducir el tiempo de entrenamiento."},{key:"D",text:"Eliminar características (features) poco importantes para simplificar el modelo."}],
  answer:"B",
  explanation:"La minimización de datos es un principio de privacidad (GDPR Art. 5): no se deben recopilar más datos personales de los necesarios para el propósito específico. En IA: ¿necesito realmente el nombre completo, o me basta con el ID de cliente? ¿necesito el historial de 10 años, o 2 son suficientes? Reduce el riesgo de brecha de privacidad y el scope de responsabilidad."},

  {id:"q370",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué son las 'tarjetas de modelo' (model cards) y por qué son importantes para la IA responsable?",
  options:[{key:"A",text:"Tarjetas de presentación que los desarrolladores de IA usan para identificarse."},{key:"B",text:"Documentos de transparencia que describen: propósito del modelo, datos de entrenamiento, rendimiento desglosado por grupos, limitaciones conocidas, sesgos identificados, casos de uso recomendados y no recomendados."},{key:"C",text:"Fichas técnicas del hardware necesario para ejecutar un modelo específico."},{key:"D",text:"Certificados de seguridad emitidos por organismos reguladores para modelos de IA."}],
  answer:"B",
  explanation:"Las model cards (Google, 2018) documentan el modelo de forma transparente: para qué fue diseñado, con qué datos fue entrenado, cómo se desempeña en diferentes grupos demográficos, limitaciones conocidas y casos de uso inapropiados. Amazon Bedrock publica información sobre los modelos disponibles. Esenciales para tomar decisiones informadas sobre qué modelo usar."},

  {id:"q371",domain:4,subdomain:"4.1",service:null,difficulty:"hard",
  question:"¿Cómo se aborda el riesgo de 'automatización de la discriminación' en sistemas de contratación con IA?",
  options:[{key:"A",text:"Eliminando completamente cualquier referencia a características demográficas en el proceso."},{key:"B",text:"Auditorías periódicas de equidad de resultados por grupos protegidos, revisión de las características usadas para detectar proxies de características protegidas, HITL para decisiones finales, documentación del proceso, y pruebas de disparate impact."},{key:"C",text:"Solo usando datos de los últimos 6 meses para evitar sesgos históricos."},{key:"D",text:"Requiriendo que todos los candidatos provengan de las mismas fuentes de reclutamiento."}],
  answer:"B",
  explanation:"Los sistemas de contratación con IA pueden discriminar de forma no obvia: un modelo entrenado en datos históricos de empleados exitosos (mayoritariamente un género/etnia) aprende que ese perfil es 'bueno'. Mitigaciones: auditar resultados de contratación por grupo, eliminar features que sean proxy de raza/género, mantener humanos en las decisiones finales, y documentar todo para auditorías regulatorias."},

  {id:"q372",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué es el 'AI Safety' (seguridad de la IA) y qué riesgos aborda?",
  options:[{key:"A",text:"La seguridad informática de los servidores que ejecutan modelos de IA."},{key:"B",text:"El campo que estudia cómo asegurar que los sistemas de IA behaven de forma alineada con la intención humana, abordando riesgos de: mal alineación de objetivos, uso malicioso, fallos en producción y, a largo plazo, sistemas superinteligentes."},{key:"C",text:"La seguridad física de las instalaciones donde se entrenan los modelos."},{key:"D",text:"Las pruebas de carga para asegurar que el modelo soporta el tráfico de producción."}],
  answer:"B",
  explanation:"AI Safety abarca: (1) Safety técnica: robustez, comportamiento predecible, fallo seguro. (2) Alineación: que el sistema haga lo que los humanos realmente quieren, no solo lo que se especificó literalmente. (3) Seguridad ante uso malicioso: deepfakes, desinformación, armas autónomas. (4) Gobernanza: regulaciones, estándares internacionales, supervisión."},

  {id:"q373",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué son los 'data sheets for datasets' y cómo apoyan el desarrollo de IA responsable?",
  options:[{key:"A",text:"Hojas de especificaciones técnicas del hardware de almacenamiento para datasets."},{key:"B",text:"Documentos que acompañan los datasets describiendo: motivación, proceso de creación, composición, recolección, preprocesamiento, distribución, mantenimiento, sesgos conocidos y casos de uso recomendados/contraindicados."},{key:"C",text:"Fichas de pago de los proveedores de datos usados en el entrenamiento."},{key:"D",text:"Inventarios de los archivos incluidos en un dataset de entrenamiento."}],
  answer:"B",
  explanation:"Los datasheets for datasets (Gebru et al., 2018) documentan de forma estándar: ¿para qué se creó el dataset? ¿cómo fue recolectado? ¿qué grupos están representados y cuáles no? ¿qué sesgos se identificaron? ¿bajo qué licencia se distribuye? Permiten a los equipos de IA tomar decisiones informadas sobre si un dataset es apropiado para su caso de uso."},

  {id:"q374",domain:4,subdomain:"4.1",service:null,difficulty:"hard",
  question:"¿Qué es el 'consent' (consentimiento) en el contexto de datos de entrenamiento para IA?",
  options:[{key:"A",text:"El acuerdo técnico entre AWS y el cliente para usar los servicios de IA."},{key:"B",text:"La autorización informada de las personas cuyos datos se usan para entrenar modelos de IA; sin consentimiento apropiado, el uso de datos personales puede violar regulaciones como GDPR y generar responsabilidad legal."},{key:"C",text:"La aprobación interna del equipo legal para desplegar un modelo de IA."},{key:"D",text:"El permiso de los reguladores para que una empresa use IA en sectores regulados."}],
  answer:"B",
  explanation:"El consentimiento es fundamental bajo GDPR: los datos personales solo pueden usarse para los propósitos para los que fueron recolectados. Problema creciente: modelos entrenados en texto de internet raspeado (Common Crawl) pueden incluir datos de personas sin consentimiento explícito para este uso. Litigios como New York Times vs. OpenAI cuestionan estos límites."},

  {id:"q375",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Cuál es el papel del 'red-teaming' en el desarrollo de IA responsable?",
  options:[{key:"A",text:"Un equipo de especialistas en redes que configura la infraestructura para el modelo."},{key:"B",text:"Un equipo dedicado a atacar el sistema de IA para encontrar vulnerabilidades de seguridad, comportamientos inesperados, sesgos, formas de generar contenido dañino y casos extremos antes del despliegue."},{key:"C",text:"Un equipo de marketing que evalúa la percepción pública del sistema de IA."},{key:"D",text:"Revisores externos que auditan la documentación del modelo para cumplimiento regulatorio."}],
  answer:"B",
  explanation:"El red-teaming de IA involucra especialistas que intentan explotar el sistema: jailbreaking, extracción de datos de entrenamiento, generación de contenido dañino, sesgos ante casos límite, comportamiento con inputs inesperados. Amazon usa red-teaming para los modelos de Bedrock. Es el método más efectivo para identificar riesgos reales antes de que los usuarios maliciosos los encuentren."},

  {id:"q376",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué es el principio de 'accountability' (responsabilidad) en la IA responsable?",
  options:[{key:"A",text:"La capacidad técnica del modelo para dar cuentas de sus cálculos internos."},{key:"B",text:"La claridad sobre quién es responsable de las decisiones tomadas por los sistemas de IA: los desarrolladores, las organizaciones que los despliegan y/o los usuarios; necesaria para remediar daños y asegurar comportamiento ético."},{key:"C",text:"El proceso de facturación mensual de los servicios de IA de AWS."},{key:"D",text:"El registro automático de todas las acciones de un modelo de IA en logs de auditoría."}],
  answer:"B",
  explanation:"La accountability en IA establece cadenas de responsabilidad: ¿quién responde si el modelo discrimina? ¿el desarrollador del modelo, la empresa que lo despliega, o ambos? El EU AI Act y otras regulaciones establecen responsabilidades explícitas. En AWS: el modelo de responsabilidad compartida aplica: AWS es responsable de la infraestructura; el cliente es responsable del uso apropiado del modelo."},

  {id:"q377",domain:4,subdomain:"4.1",service:null,difficulty:"hard",
  question:"¿Cómo debe considerarse el impacto ambiental en el desarrollo de IA responsable?",
  options:[{key:"A",text:"El impacto ambiental no es relevante para la ética de la IA."},{key:"B",text:"El alto consumo de energía y agua en el entrenamiento e inferencia de grandes modelos tiene un impacto ambiental real; la IA responsable implica: modelos eficientes, infraestructura con energía renovable, y considerar si el beneficio del modelo justifica su huella."},{key:"C",text:"Solo los data centers físicos tienen impacto ambiental; los servicios cloud no."},{key:"D",text:"AWS compensa completamente el impacto ambiental de todos los modelos en Bedrock."}],
  answer:"B",
  explanation:"El impacto ambiental de la IA incluye: energía eléctrica para entrenamiento e inferencia, agua para refrigeración de data centers, y emisiones de CO2 asociadas. La IA responsable considera: ¿es necesario un modelo grande? ¿se puede lograr el mismo resultado con uno más pequeño? AWS tiene compromisos de energía renovable (100% para 2025) y publica métricas de sostenibilidad."},

  {id:"q378",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué es el 'EU AI Act' y cómo clasifica los riesgos de los sistemas de IA?",
  options:[{key:"A",text:"Una directiva de la UE exclusivamente sobre privacidad de datos en sistemas de IA."},{key:"B",text:"El primer marco regulatorio integral de la UE para la IA, que clasifica sistemas en: riesgo inaceptable (prohibidos), alto riesgo (infraestructura crítica, empleo, educación, servicios esenciales) con requisitos estrictos, y riesgo limitado/mínimo con obligaciones ligeras."},{key:"C",text:"Un estándar técnico de la ISO para certificar la calidad de los modelos de IA."},{key:"D",text:"Una regulación que solo aplica a empresas con sede en la Unión Europea."}],
  answer:"B",
  explanation:"El EU AI Act (2024) establece: Riesgo inaceptable (prohibido): manipulación subliminal, puntuación social, reconocimiento facial en espacios públicos. Alto riesgo: sistemas en salud, empleo, crédito, educación, biometría - requieren registrarse, documentar, gestionar riesgos y transparencia. Los modelos de foundation grandes (como GPT-4, Claude) tienen requisitos adicionales de transparencia."},

  {id:"q379",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué es el 'principio de proporcionalidad' en el uso de IA para toma de decisiones?",
  options:[{key:"A",text:"La proporcionalidad entre el tamaño del modelo y la precisión requerida."},{key:"B",text:"El uso de medios de IA no más intrusivos ni invasivos de lo necesario para lograr el objetivo legítimo; los beneficios deben superar los riesgos e impactos negativos sobre los derechos de las personas."},{key:"C",text:"El equilibrio entre el costo de desarrollo y los beneficios económicos de la IA."},{key:"D",text:"La proporción correcta de datos de entrenamiento y validación."}],
  answer:"B",
  explanation:"La proporcionalidad es un principio clave de IA responsable y regulaciones como GDPR: ¿es este sistema de IA la solución mínimamente intrusiva para el problema? ¿un reconocimiento facial masivo en espacio público es proporcional al beneficio de seguridad? Implica un análisis de impacto antes de desplegar sistemas que afecten derechos fundamentales."},

  {id:"q380",domain:4,subdomain:"4.1",service:null,difficulty:"hard",
  question:"¿Qué es el 'AI Impact Assessment' y cuándo debe realizarse?",
  options:[{key:"A",text:"Una evaluación de rendimiento del modelo en un dataset de prueba."},{key:"B",text:"Una evaluación sistemática antes del despliegue que identifica los impactos potenciales del sistema de IA sobre individuos y grupos, especialmente en derechos fundamentales, privacidad, equidad y seguridad."},{key:"C",text:"Una auditoría financiera del costo de desarrollo de sistemas de IA."},{key:"D",text:"Una evaluación técnica del impacto en latencia del sistema de producción."}],
  answer:"B",
  explanation:"El AI Impact Assessment (similar al DPIA de GDPR para datos) evalúa: ¿quién puede ser afectado negativamente? ¿qué sesgos podrían amplificarse? ¿qué derechos se ven implicados? ¿qué medidas de mitigación se implementan? El EU AI Act requiere esto para sistemas de alto riesgo. AWS ofrece documentación y herramientas (Clarify) para apoyar estas evaluaciones."},

  {id:"q381",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué es la 'inclusividad' en el diseño de sistemas de IA y cómo se implementa?",
  options:[{key:"A",text:"Asegurar que el sistema de IA esté disponible en todos los países del mundo."},{key:"B",text:"Diseñar sistemas de IA que funcionen equitativamente para todos los grupos de usuarios: diferentes idiomas, capacidades, culturas y contextos socioeconómicos, evitando que los beneficios de la IA sean accesibles solo para algunos grupos privilegiados."},{key:"C",text:"Incluir a todos los empleados de la empresa en el proceso de desarrollo de IA."},{key:"D",text:"La compatibilidad del sistema de IA con todos los navegadores web modernos."}],
  answer:"B",
  explanation:"La inclusividad en IA significa: datasets que representen diversidad (géneros, etnias, edades, capacidades), interfaces accesibles (compatibilidad con lectores de pantalla, múltiples idiomas), rendimiento equitativo para todos los grupos, y precios accesibles. Ej: Amazon Rekognition inicial tenía peor rendimiento para caras femeninas y de personas de color; la inclusividad en datos lo corrigió."},

  {id:"q382",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Cuál es la responsabilidad del 'operador' (quien despliega) vs. el 'proveedor' (quien desarrolla) del modelo en la cadena de responsabilidad de IA?",
  options:[{key:"A",text:"Solo el proveedor del modelo es responsable de cualquier daño causado."},{key:"B",text:"El proveedor es responsable de la seguridad y calidad del modelo base; el operador que lo despliega en una aplicación es responsable del uso apropiado, configuración de seguridad, monitoreo y cumplimiento con las leyes de su dominio."},{key:"C",text:"Solo el usuario final es responsable del uso que hace del sistema de IA."},{key:"D",text:"No existe responsabilidad legal en el uso de sistemas de IA actualmente."}],
  answer:"B",
  explanation:"El EU AI Act establece responsabilidades diferenciadas: proveedores de modelos base (OpenAI, Anthropic, AWS) tienen obligaciones de transparencia y documentación. Operadores que despliegan en aplicaciones específicas son responsables de la adecuación para el uso, cumplimiento con leyes sectoriales (médica, financiera) y monitoreo. Los usuarios tienen responsabilidad de uso adecuado."},

  {id:"q383",domain:4,subdomain:"4.1",service:null,difficulty:"hard",
  question:"¿Qué son los 'usos prohibidos' de la IA según el EU AI Act y marcos de IA responsable?",
  options:[{key:"A",text:"El EU AI Act no prohíbe ningún uso específico de la IA."},{key:"B",text:"Sistemas que manipulan comportamiento humano de forma subliminal, sistemas de puntuación social gubernamental, identificación biométrica remota en tiempo real en espacios públicos con fines policiales, y sistemas que explotan vulnerabilidades de grupos vulnerables."},{key:"C",text:"Cualquier uso de IA en el sector público está prohibido."},{key:"D",text:"El uso de IA en aplicaciones de entretenimiento o juegos."}],
  answer:"B",
  explanation:"El EU AI Act prohíbe: (1) Sistemas de manipulación conductual subliminal, (2) Sistemas de scoring social por gobiernos, (3) Reconocimiento facial en tiempo real en espacios públicos con fines policiales (con excepciones limitadas), (4) Sistemas que explotan vulnerabilidades de niños, personas con discapacidad o situación económica precaria para influir en su comportamiento."},

  {id:"q384",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Cómo contribuye la diversidad en los equipos de desarrollo de IA a la reducción de sesgos?",
  options:[{key:"A",text:"La diversidad del equipo no tiene impacto en el sesgo del modelo."},{key:"B",text:"Equipos más diversos (género, etnia, disciplina, experiencia) identifican mejor los casos extremos, cuestionan supuestos implícitos, representan perspectivas de grupos que podrían ser afectados, y detectan sesgos que equipos homogéneos no considerarían."},{key:"C",text:"La diversidad solo importa en el equipo de evaluación, no en el de desarrollo."},{key:"D",text:"Los algoritmos de ML neutralizan automáticamente los sesgos independientemente del equipo."}],
  answer:"B",
  explanation:"Los equipos homogéneos tienen puntos ciegos: Amazon reconoció que su IA de contratación penalizaba a mujeres porque fue entrenada con datos de sus empleados históricos (predominantemente hombres). Un equipo diverso en género o etnia lo habría cuestionado antes. La diversidad en datos, equipos y criterios de evaluación es fundamental para IA más equitativa."},

  {id:"q385",domain:4,subdomain:"4.1",service:null,difficulty:"medium",
  question:"¿Qué es el principio de 'privacidad desde el diseño' (Privacy by Design) aplicado a sistemas de IA?",
  options:[{key:"A",text:"Agregar características de privacidad al sistema de IA después de su desarrollo."},{key:"B",text:"Integrar protecciones de privacidad en todas las fases del diseño y desarrollo del sistema de IA: mínima recolección de datos, anonimización/seudonimización, acceso mínimo necesario, transparencia con el usuario sobre el uso de sus datos."},{key:"C",text:"Un diseño de interfaz que no muestra datos personales al usuario final."},{key:"D",text:"La eliminación automática de datos de usuarios después de cada sesión."}],
  answer:"B",
  explanation:"Privacy by Design (Ann Cavoukian, codificado en GDPR) incorpora privacidad desde el inicio: (1) Minimización de datos, (2) Propósito limitado, (3) Anonimización cuando sea posible, (4) Acceso mínimo necesario (least privilege), (5) Transparencia al usuario, (6) Capacidad de eliminar datos. En IA: ¿necesito datos personales para entrenar? ¿puedo usar datos sintéticos o anonimizados?"},

  {id:"q386",domain:4,subdomain:"4.2",service:null,difficulty:"medium",
  question:"¿Qué es la 'explicabilidad' de un modelo de IA y por qué es importante?",
  options:[{key:"A",text:"La capacidad del modelo para generar respuestas en múltiples idiomas."},{key:"B",text:"La capacidad de describir cómo y por qué un modelo llegó a una predicción específica en términos comprensibles para humanos, esencial para confianza, auditoría, corrección de errores y cumplimiento regulatorio."},{key:"C",text:"La velocidad con que el modelo puede explicar su funcionamiento técnico."},{key:"D",text:"La documentación técnica del código fuente del modelo."}],
  answer:"B",
  explanation:"La explicabilidad es crítica en decisiones de alto impacto: ¿por qué se denegó este préstamo? ¿por qué el modelo diagnosticó esta enfermedad? Regulaciones como GDPR exigen 'derecho a explicación' para decisiones automatizadas. También ayuda a detectar y corregir sesgos. SHAP, LIME y Grad-CAM son técnicas de explicabilidad para ML clásico y deep learning."},

  {id:"q387",domain:4,subdomain:"4.2",service:null,difficulty:"medium",
  question:"¿Cuál es la diferencia entre modelos 'caja negra' (black box) y modelos 'interpretables'?",
  options:[{key:"A",text:"Los modelos de caja negra son más baratos; los interpretables son más precisos."},{key:"B",text:"Los modelos caja negra (redes neuronales profundas) tienen decisiones internas opacas y difíciles de entender; los modelos interpretables (regresión logística, árboles de decisión) tienen lógica de decisión directamente comprensible."},{key:"C",text:"Los modelos caja negra solo se usan en investigación; los interpretables en producción."},{key:"D",text:"Los modelos interpretables son siempre más precisos que los de caja negra."}],
  answer:"B",
  explanation:"Modelos interpretables: regresión logística (coeficientes = importancia de features), árbol de decisión (reglas si-entonces legibles), GAM. Caja negra: redes neuronales profundas, ensemble complejo (XGBoost con miles de árboles). Existe el dilema: los modelos más precisos suelen ser menos interpretables. Post-hoc explainability (SHAP, LIME) trata de explicar modelos complejos."},

  {id:"q388",domain:4,subdomain:"4.2",service:null,difficulty:"hard",
  question:"¿Qué es LIME (Local Interpretable Model-agnostic Explanations) y cómo funciona?",
  options:[{key:"A",text:"Un optimizador de gradiente alternativo a Adam para modelos de deep learning."},{key:"B",text:"Una técnica de explicabilidad post-hoc que aproxima localmente el comportamiento de cualquier modelo complejo con un modelo simple e interpretable (regresión lineal) para una predicción específica, perturbando el input y observando el cambio en la salida."},{key:"C",text:"Un framework de evaluación para modelos de NLP enfocado en precisión."},{key:"D",text:"Una técnica de compresión de modelos basada en aproximaciones locales de la función."}],
  answer:"B",
  explanation:"LIME: para explicar la predicción de cualquier modelo en un punto específico, genera perturbaciones del input (ej. máscaras partes del texto/imagen), observa cómo cambia la predicción, y ajusta un modelo lineal simple que aproxima el comportamiento local. Permite decir: 'el modelo predijo spam principalmente por las palabras FREE y CLICK'."},

  {id:"q389",domain:4,subdomain:"4.2",service:null,difficulty:"medium",
  question:"¿Qué es el 'feature importance' global y cómo se usa para interpretar modelos de ML?",
  options:[{key:"A",text:"La lista de características de hardware más importantes para ejecutar el modelo."},{key:"B",text:"Una métrica que cuantifica la contribución promedio de cada variable de entrada al rendimiento predictivo del modelo, ayudando a entender qué variables son más influyentes en las predicciones generales."},{key:"C",text:"La importancia de la velocidad de procesamiento de features en el pipeline de datos."},{key:"D",text:"Una métrica que indica qué features del dataset tienen más datos disponibles."}],
  answer:"B",
  explanation:"La importancia global de features dice: 'en promedio, ¿qué variable influye más en las predicciones?' Para árboles: impurity-based importance o permutation importance. Para cualquier modelo: permutation importance (aleatorizar una feature y medir la caída de rendimiento) o SHAP mean |value|. Útil para: debugging de modelos, detección de features inesperadas, y explicación de alto nivel."},

  {id:"q390",domain:4,subdomain:"4.2",service:null,difficulty:"medium",
  question:"¿Qué es el 'Grad-CAM' y para qué tipo de modelos es útil?",
  options:[{key:"A",text:"Un optimizador de gradiente avanzado para entrenamiento más eficiente de CNNs."},{key:"B",text:"Una técnica de visualización para CNNs que usa los gradientes de la última capa convolucional para producir mapas de calor que muestran qué regiones de la imagen fueron más importantes para la predicción del modelo."},{key:"C",text:"Una métrica de evaluación para modelos de generación de imágenes."},{key:"D",text:"Un algoritmo de compresión de modelos específico para visión por computadora."}],
  answer:"B",
  explanation:"Gradient-weighted Class Activation Mapping (Grad-CAM) genera un mapa de calor sobre la imagen original que muestra qué pixeles/regiones influyeron más en la clasificación del modelo. Útil para: verificar que el modelo mira las partes correctas (no aprende spurious correlations), explicar a médicos por qué el modelo detectó una anomalía en cierta área de la imagen."},

  {id:"q391",domain:4,subdomain:"4.2",service:null,difficulty:"medium",
  question:"¿Qué es la 'transparencia' en los sistemas de IA y cómo se diferencia de la 'explicabilidad'?",
  options:[{key:"A",text:"Transparencia y explicabilidad son sinónimos perfectos."},{key:"B",text:"Transparencia es informar a los usuarios que están interactuando con IA, divulgar cómo funciona el sistema a nivel general y qué datos usa; explicabilidad es poder detallar por qué el modelo tomó una decisión específica."},{key:"C",text:"La transparencia aplica solo a datos; la explicabilidad aplica solo a los algoritmos."},{key:"D",text:"La transparencia requiere revelar el código fuente completo del modelo."}],
  answer:"B",
  explanation:"Transparencia (macro nivel): informar al usuario que habla con un bot, publicar la política de uso de datos, revelar que las decisiones son asistidas por IA. Explicabilidad (micro nivel): para esta decisión específica de crédito, los factores fueron X, Y, Z. El EU AI Act requiere ambas: transparencia sobre el uso de IA y explicabilidad de decisiones de alto riesgo."},

  {id:"q392",domain:4,subdomain:"4.2",service:null,difficulty:"hard",
  question:"¿Cómo se abordan los problemas de explicabilidad específicamente en los LLMs?",
  options:[{key:"A",text:"Los LLMs no necesitan explicabilidad porque son demasiado complejos para entenderse."},{key:"B",text:"Técnicas: attention visualization (ver qué tokens atiende el modelo), saliency maps, activation patching, y métodos emergentes como chain-of-thought (el modelo explica su razonamiento), aunque la explicabilidad completa de LLMs sigue siendo un área de investigación abierta."},{key:"C",text:"Los LLMs siempre explican automáticamente sus decisiones sin necesidad de técnicas adicionales."},{key:"D",text:"Se usa SHAP directamente sobre los tokens del LLM igual que en ML clásico."}],
  answer:"B",
  explanation:"La explicabilidad de LLMs es un área de investigación activa: Attention visualization muestra qué palabras atiende el modelo pero es proxy imperfecto de causalidad. Chain-of-thought es la forma más práctica de explicabilidad: el modelo muestra su razonamiento. Mechanistic interpretability (Anthropic) analiza circuitos internos del modelo. Aún no existe una solución definitiva al problema."},

  {id:"q393",domain:4,subdomain:"4.2",service:null,difficulty:"medium",
  question:"¿Qué implica el 'derecho a explicación' del GDPR para sistemas de decisión automatizada con IA?",
  options:[{key:"A",text:"El GDPR no incluye ningún derecho relacionado con IA."},{key:"B",text:"El Art. 22 del GDPR establece el derecho de los individuos a no ser sujetos de decisiones basadas únicamente en procesamiento automatizado y a recibir explicaciones significativas sobre la lógica, importancia y consecuencias de tales decisiones."},{key:"C",text:"El derecho a explicación aplica solo a empresas con más de 500 empleados."},{key:"D",text:"Solo aplica a decisiones sobre datos biométricos, no a otros tipos de datos."}],
  answer:"B",
  explanation:"GDPR Art. 22 da derecho a: (1) No ser objeto de decisiones exclusivamente automatizadas con efectos legales o significativos, (2) Intervención humana, (3) Expresar el punto de vista propio, (4) Impugnar la decisión. Para IA en crédito, empleo o servicios sociales, las empresas deben ser capaces de explicar los factores que llevaron a la decisión."},

  {id:"q394",domain:4,subdomain:"4.2",service:null,difficulty:"hard",
  question:"¿Qué es el 'interpretability vs accuracy tradeoff' y cómo debe abordarse en aplicaciones de alto riesgo?",
  options:[{key:"A",text:"La interpretabilidad siempre reduce la precisión; en aplicaciones de alto riesgo se debe priorizar precisión."},{key:"B",text:"Los modelos más interpretables (regresión logística, árboles simples) suelen ser menos precisos; los complejos (deep learning) son más precisos pero opacos. En aplicaciones de alto riesgo, la explicabilidad puede ser un requisito no negociable que justifica sacrificar algo de precisión."},{key:"C",text:"Los modelos interpretables siempre son más precisos en aplicaciones de alto riesgo."},{key:"D",text:"El tradeoff no existe; con suficientes datos cualquier modelo es interpretable y preciso."}],
  answer:"B",
  explanation:"En crédito, medicina y justicia, la explicabilidad puede ser legalmente requerida (GDPR, Equal Credit Opportunity Act). Estrategias: (1) Usar modelos interpretables cuando la brecha de precisión es pequeña. (2) Post-hoc explainability (SHAP/LIME) para modelos complejos. (3) Modelos inherentemente interpretables pero potentes (EBM, Explainable Boosting Machine). El regulador puede requerir modelos explicables sobre modelos más precisos."},

  {id:"q395",domain:4,subdomain:"4.2",service:null,difficulty:"medium",
  question:"¿Qué es la 'trazabilidad' (traceability) en el contexto de IA responsable y cómo se implementa?",
  options:[{key:"A",text:"La capacidad de rastrear el tráfico de red entre el usuario y el servidor del modelo."},{key:"B",text:"La capacidad de rastrear el linaje completo de un sistema de IA: origen de los datos, proceso de entrenamiento, versiones del modelo, decisiones en producción y cambios a lo largo del tiempo; implementada con versionado, logging y metadata."},{key:"C",text:"El seguimiento de las peticiones de soporte técnico relacionadas con el sistema de IA."},{key:"D",text:"La función de seguimiento de paquetes para hardware de servidores de IA."}],
  answer:"B",
  explanation:"La trazabilidad en IA implica: (1) Linaje de datos (DVC, SageMaker Feature Store), (2) Versionado de modelos (SageMaker Model Registry), (3) Registro de hiperparámetros y métricas (SageMaker Experiments), (4) Auditoría de predicciones en producción (Model Monitor, CloudTrail), (5) Linaje del pipeline (SageMaker Pipelines). Esencial para auditorías regulatorias y debugging."}
];
